### ISSUE TITLE
运行环境

### ISSUE THREAD

**Issue by WenmuZhou** [ouyanghuiyu/chineseocr_lite#1]
请问运行环境是怎样的

**Comment by ouyanghuiyu** [comment]
torch 1.2.0

**Comment by WenmuZhou** [comment]
支持windows不

**Comment by ouyanghuiyu** [comment]
我没试过 我是用linux的！ 我是就有https://github.com/chineseocr/chineseocr这个项目，该项目支持就应该支持。 如果不搭web服务 应该肯定能支持
