### ISSUE TITLE
你好 请问crnn_lite和crnn，最终精度差多少呢？

### ISSUE THREAD

**Issue by ZimingLu** [ouyanghuiyu/chineseocr_lite#10]

**Comment by ouyanghuiyu** [comment]
crnn我自己没训练，和chineseocr作者训练的数据集也不一样，就没做具体对比

**Comment by Letter24** [comment]
> crnn我自己没训练，和chineseocr作者训练的数据集也不一样，就没做具体对比

老师，crnn_lite的模型是用那个工程训练的？我想训练自己的数据集
