### ISSUE TITLE
404 not find

### ISSUE THREAD

**Issue by jameswangcnbj** [ouyanghuiyu/chineseocr_lite#108]
编译完成pse，运行app.py
(torch-ocr) [root@etl chineseocr_lite]# python app.py 8080
make: 进入目录“/root/chineseocr_lite/psenet/pse”
make: “pse.so”是最新的。
make: 离开目录“/root/chineseocr_lite/psenet/pse”
device: cpu
load model
device: cpu
load model
device: cpu
load model
device: cpu
load model
http://0.0.0.0:8080/
10.172.192.92:18160 - - [02/Apr/2020 09:27:28] "HTTP/1.1 GET /" - 404 Not Found
10.172.192.92:18160 - - [02/Apr/2020 09:27:31] "HTTP/1.1 GET /" - 404 Not Found

**Comment by jameswangcnbj** [comment]
自己找到原因了，地址/ocr

**Comment by mad-fogs** [comment]
hi how did u solve this issue?
