### ISSUE TITLE
ncnn检测识别怎么操作

### ISSUE THREAD

**Issue by Lie-huo** [ouyanghuiyu/chineseocr_lite#11]
您好，ncnn检测识别怎么操作呢，可不可以说一下具体的执行步骤呢？

**Comment by ouyanghuiyu** [comment]
待会我在readme里面更新一下

**Comment by ouyanghuiyu** [comment]
> 您好，ncnn检测识别怎么操作呢，可不可以说一下具体的执行步骤呢？

在ocr目录下的redame已经写了操作
