### ISSUE TITLE
关于自己重训练的模型速度过慢的问题

### ISSUE THREAD

**Issue by Arctanxy** [ouyanghuiyu/chineseocr_lite#113]
大佬你好，我在安卓模拟器上测试了您的psenet速度在1.5s-2s范围，而我利用wenmuzhou/pytorch项目中提供的mobilenetv3代码训练出一个6MB多的psenet，速度却在5-7s范围。

想问下您的psnet做过哪些优化呢？

**Comment by ouyanghuiyu** [comment]
具体你可以看一下我的psenet网络结构吧
