### ISSUE TITLE
在mac上运行出错

### ISSUE THREAD

**Issue by lxj0276** [ouyanghuiyu/chineseocr_lite#12]
出错信息：Segmentation fault: 11
位置是：psenet/PSENET.py 中 preds, boxes_list,rects  =  pse_decode(preds[0], self.scale)
不知道是否可以fix一下。。

**Comment by ouyanghuiyu** [comment]
> 出错信息：Segmentation fault: 11
> 位置是：psenet/PSENET.py 中 preds, boxes_list,rects = pse_decode(preds[0], self.scale)
> 不知道是否可以fix一下。。

我也遇到过这问题，重新编译一下pse模块，要保证编译python.m的版本和你运行的python版本一直

**Comment by lxj0276** [comment]
再问一个比较傻的问题，python.m在哪里。。

**Comment by ouyanghuiyu** [comment]
> 再问一个比较傻的问题，python.m在哪里。。

编译pse模块的时候出现的这个
![image](https://user-images.githubusercontent.com/42023607/76142856-a3fb0580-60ac-11ea-9afa-d55bdd3c251f.png)

**Comment by meitianjinbu** [comment]
> > 再问一个比较傻的问题，python.m在哪里。。
> 
> 编译pse模块的时候出现的这个
> ![image](https://user-images.githubusercontent.com/42023607/76142856-a3fb0580-60ac-11ea-9afa-d55bdd3c251f.png)

我在mac下，pse编译用的是3.7m，运行也是3.7的，也还是报错。
运行的时候报段错误。debug定位是在from .pse import pse_cpp错误，应该是so编译还是有问题。不知道作者有碰到过这样的问题么？

**Comment by Johnson-yue** [comment]
我在mac上编译pse。so 就没有成功。貌似 mac上面用clang和g++还不一样
我的报错信息是
![image](https://user-images.githubusercontent.com/10268274/76393995-afea0e80-63af-11ea-93c3-65983ae9a61b.png)

**Comment by lxj0276** [comment]
> 我在mac上编译pse。so 就没有成功。貌似 mac上面用clang和g++还不一样
> 我的报错信息是
> ![image](https://user-images.githubusercontent.com/10268274/76393995-afea0e80-63af-11ea-93c3-65983ae9a61b.png)

解决了吆喝一声，我也没解决，我发现用 python2.7版本可以编译通过

**Comment by clnFind** [comment]
> 我在mac上编译pse。so 就没有成功。貌似 mac上面用clang和g++还不一样
> 我的报错信息是
> ![image](https://user-images.githubusercontent.com/10268274/76393995-afea0e80-63af-11ea-93c3-65983ae9a61b.png)

请问解决了吗？我也遇到同样的问题。

**Comment by Johnson-yue** [comment]
@lxj0276 @clnFind 不好意思，还没有解决，我在ubuntu上测试了一下效果，不是很好，所以我就暂时放弃了这个方案

**Comment by xiaoliuit** [comment]
python app.py 8080 成功
可以通过8080端口访问
但是上传图片时报错了  Segmentation fault

**Comment by killuayang90s** [comment]
![image](https://user-images.githubusercontent.com/49148415/140057054-cfcc2459-63ea-4219-b328-a5f27f93de34.png)
mac上编译报错....有有效的解决办法吗？
