### ISSUE TITLE
是否存在内存泄漏？

### ISSUE THREAD

**Issue by lijingbo8119** [ouyanghuiyu/chineseocr_lite#127]
在服务器上（2核CPU 4G内存）通过docker搭建了一下，通过web访问 /ocr 每识别一个图片大概要涨10%-20%的内存。识别完成之后内存也不会下降。导致每识别n个图片都需要重启web服务。

对python不太熟悉，没法通过查看源码判断是否存在内存泄漏或者资源未释放的问题。

**Comment by lijingbo8119** [comment]
![image](https://user-images.githubusercontent.com/33534410/79834771-36970000-83e0-11ea-9eaa-d108ce44c236.png)

**Comment by xisi789** [comment]
我也发现用pytorch版本有这个问题，你解决了吗？

**Comment by lijingbo8119** [comment]
没有解决。环境是通过docker自动搭建的。
如果是pytorch的问题我试试更换版本看看能否解决～

**Comment by xisi789** [comment]
> 没有解决。环境是通过docker自动搭建的。
> 如果是pytorch的问题我试试更换版本看看能否解决～
问题解决了吗？怎么关掉了呀？
