### ISSUE TITLE
缺少包

### ISSUE THREAD

**Issue by XiaotianDong** [ouyanghuiyu/chineseocr_lite#13]
Traceback (most recent call last):
  File "C:\Users\Administrator\Downloads\chineseocr_lite-master\app.py", line 8, in <module>
    import web
ModuleNotFoundError: No module named 'web'
缺少了web.py?
我是在Windows7 python3.7.4 x64下运行的

**Comment by ouyanghuiyu** [comment]
requirements.txt 里面有相关包，安装一下啊

**Comment by XiaotianDong** [comment]
我安装了，但好像在安装vc时失败报错了，并且我尝试直接pip安装web也报错



dongxiaotian123456@outlook.com
 
发件人： ouyanghuiyu
发送时间： 2020-03-08 11:13
收件人： ouyanghuiyu/chineseocr_lite
抄送： 董晓天; Author
主题： Re: [ouyanghuiyu/chineseocr_lite] 缺少包 (#13)
requirements.txt 里面有相关包，安装一下啊
―

**Comment by ouyanghuiyu** [comment]
> 我安装了，但好像在安装vc时失败报错了，并且我尝试直接pip安装web也报错 dongxiaotian123456@outlook.com 发件人： ouyanghuiyu 发送时间： 2020-03-08 11:13 收件人： ouyanghuiyu/chineseocr_lite 抄送： 董晓天; Author 主题： Re: [ouyanghuiyu/chineseocr_lite] 缺少包 (#13) requirements.txt 里面有相关包，安装一下啊 ― You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我只在macos/linux 进行了测试，windows可能有点问题
