### ISSUE TITLE
如何切换到纯英文模型或者使用ocr-english模型？

### ISSUE THREAD

**Issue by kekira2714** [ouyanghuiyu/chineseocr_lite#136]
是否在config.py中 可以切换模型到纯英文 或者调用使用chineseocr的ocr-english模型？

**Comment by ouyanghuiyu** [comment]
是可以用chineseocr中的模型的，你可以自己修改一下

**Comment by kekira2714** [comment]
如何切换到gpu模式的，修改GPU_ID= "显卡设备id"？ 貌似不对
