### ISSUE TITLE
psenet编译报错

### ISSUE THREAD

**Issue by WestbrookZero** [ouyanghuiyu/chineseocr_lite#14]
make
g++ -o pse.so -I include  -std=c++11 -O3 -I/home/wuqiang/anaconda3/envs/OCR00/include/python3.6m -I/home/wuqiang/anaconda3/envs/OCR00/include/python3.6m  -Wno-unused-result -Wsign-compare -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -ffunction-sections -pipe  -fdebug-prefix-map=/tmp/build/80754af9/python_1564510748219/work=/usr/local/src/conda/python-3.6.9 -fdebug-prefix-map=/home/wuqiang/anaconda3/envs/OCR00=/usr/local/src/conda-prefix -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -flto -DNDEBUG -fwrapv -O3 -Wall -L/home/wuqiang/anaconda3/envs/OCR00/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/home/wuqiang/anaconda3/envs/OCR00/lib -lpython3.6m -lpthread -ldl  -lutil -lrt -lm  -Xlinker -export-dynamic pse.cpp --shared -fPIC
g++: error: unrecognized command line option ‘-fno-plt’
Makefile:10: recipe for target 'pse.so' failed
make: *** [pse.so] Error 1

**Comment by miming1688** [comment]
在linux下出现相同的错误.请作者帮一下,谢谢.
make
g++ -o pse.so -I include  -std=c++11 -O3 -I/root/anaconda3/include/python3.7m -I/root/anaconda3/include/python3.7m  -Wno-unused-result -Wsign-compare -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -ffunction-sections -pipe  -fdebug-prefix-map=/tmp/build/80754af9/python_1565725737370/work=/usr/local/src/conda/python-3.7.4 -fdebug-prefix-map=/root/anaconda3=/usr/local/src/conda-prefix -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -flto -DNDEBUG -fwrapv -O3 -Wall -L/root/anaconda3/lib/python3.7/config-3.7m-x86_64-linux-gnu -L/root/anaconda3/lib -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lrt -lm  pse.cpp --shared -fPIC
g++: 错误：unrecognized command line option ‘-fno-plt’
make: *** [pse.so] 错误 1

**Comment by ouyanghuiyu** [comment]
> g++: 错误：unrecognized command line option ‘-fno-plt’

你可以尝试直接复制make命令 将-fno-plt 删除 
g++ -o pse.so -I include -std=c++11 -O3 -I/home/wuqiang/anaconda3/envs/OCR00/include/python3.6m -I/home/wuqiang/anaconda3/envs/OCR00/include/python3.6m -Wno-unused-result -Wsign-compare -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -O3 -ffunction-sections -pipe -fdebug-prefix-map=/tmp/build/80754af9/python_1564510748219/work=/usr/local/src/conda/python-3.6.9 -fdebug-prefix-map=/home/wuqiang/anaconda3/envs/OCR00=/usr/local/src/conda-prefix -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -flto -DNDEBUG -fwrapv -O3 -Wall -L/home/wuqiang/anaconda3/envs/OCR00/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/home/wuqiang/anaconda3/envs/OCR00/lib -lpython3.6m -lpthread -ldl -lutil -lrt -lm -Xlinker -export-dynamic pse.cpp --shared -fPIC

**Comment by DarrenLee618** [comment]
在pse路径下执行 python3-config --cflags，将执行的结果路径替换Makefile里面的 $(shell python3-config --cflags)，试一下

**Comment by Yangxiaojun1230** [comment]
I met the error couldn't find python.h , then i apt-get python-dev out of conda env, but the error was same. Anyone know the way? 
Ubuntu 16.04
pytorch-1.4

**Comment by DarrenLee618** [comment]
> I met the error couldn't find python.h , then i apt-get python-dev out of conda env, but the error was same. Anyone know the way?
> Ubuntu 16.04
> pytorch-1.4

If your python version is python3 ,installing python-dev on Ubuntu , maybe you need to attach
the python version number.  Try apt-get python [ PYTHON VERSION ]-dev, eg:apt-get python3.6-dev

**Comment by Yangxiaojun1230** [comment]
The approach I reached was to modify the common.h to define the path of Python.h. Since in python-dev didn't install in /usr/include but in /usr/include/python3.6.

**Comment by FankLi** [comment]
> > g++: 错误：unrecognized command line option ‘-fno-plt’
> 
> 你可以尝试直接复制make命令 将-fno-plt 删除
> g++ -o pse.so -I include -std=c++11 -O3 -I/home/wuqiang/anaconda3/envs/OCR00/include/python3.6m -I/home/wuqiang/anaconda3/envs/OCR00/include/python3.6m -Wno-unused-result -Wsign-compare -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -O3 -ffunction-sections -pipe -fdebug-prefix-map=/tmp/build/80754af9/python_1564510748219/work=/usr/local/src/conda/python-3.6.9 -fdebug-prefix-map=/home/wuqiang/anaconda3/envs/OCR00=/usr/local/src/conda-prefix -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -flto -DNDEBUG -fwrapv -O3 -Wall -L/home/wuqiang/anaconda3/envs/OCR00/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/home/wuqiang/anaconda3/envs/OCR00/lib -lpython3.6m -lpthread -ldl -lutil -lrt -lm -Xlinker -export-dynamic pse.cpp --shared -fPIC
没有看明白，可以详细说一下吗，期待你的回复

**Comment by FankLi** [comment]
> > g++: 错误：unrecognized command line option ‘-fno-plt’
> 
> 你可以尝试直接复制make命令 将-fno-plt 删除
> g++ -o pse.so -I include -std=c++11 -O3 -I/home/wuqiang/anaconda3/envs/OCR00/include/python3.6m -I/home/wuqiang/anaconda3/envs/OCR00/include/python3.6m -Wno-unused-result -Wsign-compare -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -O3 -ffunction-sections -pipe -fdebug-prefix-map=/tmp/build/80754af9/python_1564510748219/work=/usr/local/src/conda/python-3.6.9 -fdebug-prefix-map=/home/wuqiang/anaconda3/envs/OCR00=/usr/local/src/conda-prefix -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -flto -DNDEBUG -fwrapv -O3 -Wall -L/home/wuqiang/anaconda3/envs/OCR00/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/home/wuqiang/anaconda3/envs/OCR00/lib -lpython3.6m -lpthread -ldl -lutil -lrt -lm -Xlinker -export-dynamic pse.cpp --shared -fPIC

没有看明白，可以详细说一下吗，期待你的回复

**Comment by kiclent** [comment]
参考：https://blog.csdn.net/u011489887/article/details/89329750
1.报错如下：
ImportError: /home/yang/Documents/model/detect/PSENet-master/pse/adaptor.so: undefined symbol: _Py_ZeroStruct

一般来说是编译环境版本不对应的问题。

于是修改pse/include/pybind11/detail/common.h中的第112~114：

#include <python2.7/Python.h>

#include <python2.7/frameobject.h>

#include <python2.7/pythread.h>

为：

#include <python3.5/Python.h>

#include <python3.5/frameobject.h>

#include <python3.5/pythread.h>

**Comment by vba34520** [comment]
Windows下的编译欢迎查阅[Python构建快速高效的中文文字识别OCR](https://blog.csdn.net/lly1122334/article/details/104752851)，感谢#50 DarrenLee618大佬

**Comment by li-x-q** [comment]
> g++: 错误：unrecognized command line option ‘-fno-plt’
> 
> 你可以尝试直接复制make命令 将-fno-plt 删除
> g++ -o pse.so -I include -std=c++11 -O3 -I/home/wuqiang/anaconda3/envs/OCR00/include/python3.6m -I/home/wuqiang/anaconda3/envs/OCR00/include/python3.6m -Wno-unused-result -Wsign-compare -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -O3 -ffunction-sections -pipe -fdebug-prefix-map=/tmp/build/80754af9/python_1564510748219/work=/usr/local/src/conda/python-3.6.9 -fdebug-prefix-map=/home/wuqiang/anaconda3/envs/OCR00=/usr/local/src/conda-prefix -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -flto -DNDEBUG -fwrapv -O3 -Wall -L/home/wuqiang/anaconda3/envs/OCR00/lib/python3.6/config-3.6m-x86_64-linux-gnu -L/home/wuqiang/anaconda3/envs/OCR00/lib -lpython3.6m -lpthread -ldl -lutil -lrt -lm -Xlinker -export-dynamic pse.cpp --shared -fPIC
> 
> 没有看明白，可以详细说一下吗，期待你的回复

直接复制那一大堆命令（删除其中的-fno-plt参数）在命令行执行
