### ISSUE TITLE
您好，该怎么理解文本方向的四个分类呢？

### ISSUE THREAD

**Issue by learn01one** [ouyanghuiyu/chineseocr_lite#15]
lable_map_dict  =  { 0 : "hengdao",  1:"hengzhen",  2:"shudao",  3:"shuzhen"}
rotae_map_dict  =   {"hengdao": 180 , "hengzhen": 0 , "shudao": 180 , "shuzhen": 0 }

**Comment by ouyanghuiyu** [comment]
可以参考https://github.com/ouyanghuiyu/chineseocr_lite/issues/5
