### ISSUE TITLE
windows  下  执行make报错

### ISSUE THREAD

**Issue by jsycshanhongyu** [ouyanghuiyu/chineseocr_lite#16]
D:\chineseocrlite\chineseocr_lite-master\psenet\pse>make
FIND: 参数格式不正确
process_begin: CreateProcess(NULL, python3-config --cflags, ...) failed.
process_begin: CreateProcess(NULL, python3-config --ldflags, ...) failed.
g++ -o pse.so -I include  -std=c++11 -O3   pse.cpp --shared -fPIC
In file included from include/pybind11/pytypes.h:12:0,
                 from include/pybind11/cast.h:13,
                 from include/pybind11/attr.h:13,
                 from include/pybind11/pybind11.h:44,
                 from pse.cpp:8:
include/pybind11/detail/common.h:112:20: fatal error: Python.h: No such file or
directory
 #include <Python.h>
                    ^
compilation terminated.
Makefile:10: recipe for target 'pse.so' failed
make: *** [pse.so] Error 1

**Comment by ouyanghuiyu** [comment]
目前只支持 macos/linux

**Comment by yunnet** [comment]
可以在win10上安装docker desktop 安装使用容器跑。

**Comment by yanang007** [comment]
装上python3-dev试试，看起来是缺了这个

**Comment by vba34520** [comment]
欢迎查阅[Python构建快速高效的中文文字识别OCR](https://blog.csdn.net/lly1122334/article/details/104752851)，感谢#50 DarrenLee618大佬
