### ISSUE TITLE
win10上ncnn_project编译不过去

### ISSUE THREAD

**Issue by jayle19930918** [ouyanghuiyu/chineseocr_lite#160]
我在linux上编译过去了，识别效果很好。然后我在windows上编译了64位的ncnn，然后编译该项目，但是一直编译不过去，报以下错误：

2>ocr.obj : error LNK2019: 无法解析的外部符号 "public: static class ncnn::Mat __cdecl ncnn::Mat::from_pixels(unsigned char const *,int,int,int,class ncnn::Allocator *)" (?from_pixels@Mat@ncnn@@SA?AV12@PEBEHHHPEAVAllocator@2@@Z)，该符号在函数 "public: void __cdecl OCR::detect(class cv::Mat,int)" (?detect@OCR@@QEAAXVMat@cv@@H@Z) 中被引用
2>ocr.obj : error LNK2019: 无法解析的外部符号 "public: static class ncnn::Mat __cdecl ncnn::Mat::from_pixels_resize(unsigned char const *,int,int,int,int,int,class ncnn::Allocator *)" (?from_pixels_resize@Mat@ncnn@@SA?AV12@PEBEHHHHHPEAVAllocator@2@@Z)，该符号在函数 "public: void __cdecl OCR::detect(class cv::Mat,int)" (?detect@OCR@@QEAAXVMat@cv@@H@Z) 中被引用
2>ocr.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl ncnn::Mat::substract_mean_normalize(float const *,float const *)" (?substract_mean_normalize@Mat@ncnn@@QEAAXPEBM0@Z)，该符号在函数 "public: void __cdecl OCR::detect(class cv::Mat,int)" (?detect@OCR@@QEAAXVMat@cv@@H@Z) 中被引用
2>ocr.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl ncnn::Net::Net(void)" (??0Net@ncnn@@QEAA@XZ)，该符号在函数 "public: __cdecl OCR::OCR(void)" (??0OCR@@QEAA@XZ) 中被引用
2>ocr.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl ncnn::Net::~Net(void)" (??1Net@ncnn@@QEAA@XZ)，该符号在函数 "int `public: __cdecl OCR::OCR(void)'::`1'::dtor$0" (?dtor$0@?0???0OCR@@QEAA@XZ@4HA) 中被引用
2>ocr.obj : error LNK2019: 无法解析的外部符号 "public: int __cdecl ncnn::Net::load_param(char const *)" (?load_param@Net@ncnn@@QEAAHPEBD@Z)，该符号在函数 "public: __cdecl OCR::OCR(void)" (??0OCR@@QEAA@XZ) 中被引用
2>ocr.obj : error LNK2019: 无法解析的外部符号 "public: int __cdecl ncnn::Net::load_model(char const *)" (?load_model@Net@ncnn@@QEAAHPEBD@Z)，该符号在函数 "public: __cdecl OCR::OCR(void)" (??0OCR@@QEAA@XZ) 中被引用
2>ocr.obj : error LNK2019: 无法解析的外部符号 "public: class ncnn::Extractor __cdecl ncnn::Net::create_extractor(void)const " (?create_extractor@Net@ncnn@@QEBA?AVExtractor@2@XZ)，该符号在函数 "public: void __cdecl OCR::detect(class cv::Mat,int)" (?detect@OCR@@QEAAXVMat@cv@@H@Z) 中被引用
2>ocr.obj : error LNK2019: 无法解析的外部符号 "public: __cdecl ncnn::Extractor::~Extractor(void)" (??1Extractor@ncnn@@QEAA@XZ)，该符号在函数 "public: void __cdecl OCR::detect(class cv::Mat,int)" (?detect@OCR@@QEAAXVMat@cv@@H@Z) 中被引用
2>ocr.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl ncnn::Extractor::set_num_threads(int)" (?set_num_threads@Extractor@ncnn@@QEAAXH@Z)，该符号在函数 "public: void __cdecl OCR::detect(class cv::Mat,int)" (?detect@OCR@@QEAAXVMat@cv@@H@Z) 中被引用
2>ocr.obj : error LNK2019: 无法解析的外部符号 "public: int __cdecl ncnn::Extractor::input(char const *,class ncnn::Mat const &)" (?input@Extractor@ncnn@@QEAAHPEBDAEBVMat@2@@Z)，该符号在函数 "public: void __cdecl OCR::detect(class cv::Mat,int)" (?detect@OCR@@QEAAXVMat@cv@@H@Z) 中被引用
2>ocr.obj : error LNK2019: 无法解析的外部符号 "public: int __cdecl ncnn::Extractor::extract(char const *,class ncnn::Mat &)" (?extract@Extractor@ncnn@@QEAAHPEBDAEAVMat@2@@Z)，该符号在函数 "public: void __cdecl OCR::detect(class cv::Mat,int)" (?detect@OCR@@QEAAXVMat@cv@@H@Z) 中被引用
_2>E:\github\ncnn_ocr\ocr_lite\chineseocr_lite-master\ncnn_project\ocr\ncnn\lib\ncnn.lib : warning LNK4272: 库计算机类型“x86”与目标计算机类型“x64”冲突
2>E:\github\ncnn_ocr\ocr_lite\chineseocr_lite-master\ncnn_project\ocr\build\Release\Text_recognition.exe : fatal error LNK1120: 12 个无法解析的外部命令_

ncnn.lib应该没什么问题，却显示 库计算机类型“x86”与目标计算机类型“x64”冲突，实在是想不通啊。

**Comment by jayle19930918** [comment]
现在编过去了，但是文字识别失败

**Comment by jayle19930918** [comment]
识别失败：
senet鍓嶅悜鏃堕棿:1.02724s
psenet decode 鏃堕棿:0.0253164s
boxzie2
棰勬祴缁撴灉锛歕n
E:\github\ncnn_ocr\ocr_lite\chineseocr_lite-master\ncnn_project\ocr\build\Release\Text_recognition.exe (进程 18544)已退 出，返回代码为: -1073741819。

**Comment by jayle19930918** [comment]
跟中文字符有关系，windows上也能得到正确结果了

**Comment by CallHoganZhang** [comment]
> ncnn.lib应该没什么问题，却显示 库计算机类型“x86”与目标计算机类型“x64”冲突，实在是想不通啊。

我在win7,64位上编译后，也遇到，ncnn.lib与 库计算机类型“x86”与目标计算机类型“x64”冲突，请问你是怎么解决的呢

**Comment by littleSpongebob** [comment]
你好，有详细的ncnn_project的编译流程么，我这边好像一直搞不定，不知道是不是opencv的原因，还是真他原因，如果能告知，万分感谢

**Comment by littleSpongebob** [comment]
> > ncnn.lib应该没什么问题，却显示 库计算机类型“x86”与目标计算机类型“x64”冲突，实在是想不通啊。
> 
> 我在win7,64位上编译后，也遇到，ncnn.lib与 库计算机类型“x86”与目标计算机类型“x64”冲突，请问你是怎么解决的呢

你好你编译成功了么，望指教

**Comment by zlszhonglongshen** [comment]
> 跟中文字符有关系，windows上也能得到正确结果了

大佬 怎么搞的  能发一个自己的工程嘛
