### ISSUE TITLE
ncnn 工程中，long_size都是什么值？

### ISSUE THREAD

**Issue by xinsuinizhuan** [ouyanghuiyu/chineseocr_lite#164]
chineseocr_lite-master\ncnn_project\psenet\mian.cpp中：
 const char *model = argv[1];
    const char *model_param = argv[2];
    const char *imagepath = argv[3];
    const int long_size = atoi(argv[4]);
    std::cout << model << " " << model_param << " " << imagepath << " " << long_size << std::endl;

    detect_psenet(model, model_param, imagepath, long_size);
中long_size是什么值？我设置成图片的长边后，检测出来是乱码。

**Comment by ouyanghuiyu** [comment]
resize的长边长度
