### ISSUE TITLE
竖直文本识别

### ISSUE THREAD

**Issue by mayaya1** [ouyanghuiyu/chineseocr_lite#166]
你好，想问一下，竖直文本识别的添加是通过怎样的流程实现的，旋转样本重新训练嘛? 没有在代码中找到相应的部分，能不能告知一下，谢谢

**Comment by ouyanghuiyu** [comment]
我提供了旋转字体：https://github.com/ouyanghuiyu/chineseocr_lite/tree/master/vertical_text_fonts
