### ISSUE TITLE
请问作者有尝试openvino吗？

### ISSUE THREAD

**Issue by LJXLJXLJX** [ouyanghuiyu/chineseocr_lite#17]
ncnn不支持lstm，openvino好像可以。

**Comment by ouyanghuiyu** [comment]
> ncnn不支持lstm，openvino好像可以。

我对openvino不熟悉，正在尝试mnn，貌似mnn也支持

**Comment by LJXLJXLJX** [comment]
@ouyanghuiyu 我去年折腾过，当时MNN还不支持x86。现在说不定可以了。

**Comment by ouyanghuiyu** [comment]
> @ouyanghuiyu 我去年折腾过，当时MNN还不支持x86。现在说不定可以了。

我retinaface试过，在x86是可以的

**Comment by nihui** [comment]
https://github.com/Tencent/ncnn/pull/1613
https://github.com/ouyanghuiyu/chineseocr_lite/pull/41

我把lstm搞好了

**Comment by thomaszheng** [comment]
> > ncnn不支持lstm，openvino好像可以。
> 
> 我对openvino不熟悉，正在尝试mnn，貌似mnn也支持

请问使用mnn的可以吗？性能和ncnn对比咋样？
