### ISSUE TITLE
竖排文字的ttfs是怎么生成的？或者在哪里可以下载到？

### ISSUE THREAD

**Issue by huangjinxian0918** [ouyanghuiyu/chineseocr_lite#172]
竖排文字的ttfs是怎么生成的？或者在哪里可以下载到？

**Comment by ouyanghuiyu** [comment]
@huangjinxian0918 项目中有的

**Comment by ouyanghuiyu** [comment]
https://github.com/ouyanghuiyu/chineseocr_lite/tree/master/vertical_text_fonts/fonts

**Comment by huangjinxian0918** [comment]
我知道您项目里面有十个ttc 字体  ,   但是我想问  您这个是怎么处理的 、、、我这边只能知道横排的ttf/ttc?  或者是在哪里可以下载呢

**Comment by ouyanghuiyu** [comment]
@huangjinxian0918 使用FontForge处理的
