### ISSUE TITLE
启动的时候，提示ModuleNotFoundError: No module named 'text'

### ISSUE THREAD

**Issue by hnwlxywns** [ouyanghuiyu/chineseocr_lite#18]
[root@localhost chineseocr_lite-master]# python3.6 main.py 8080
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    from text.detector.detectors import TextDetector
ModuleNotFoundError: No module named 'text'

然后报错了，请教一下，我这边 执行安装了命令：pip3 install -i https://pypi.tuna.tsinghua.edu.cn/simple -r requirements.txt

请教一下是什么库没有安装么？

**Comment by ouyanghuiyu** [comment]
运行app.py 那个main没用 不小心放上去了

**Comment by hnwlxywns** [comment]
好的
