### ISSUE TITLE
请问一下支持火车票、身份证识别吗？为啥我这边测试，识别效果很差

### ISSUE THREAD

**Issue by JohnnyZhang0628** [ouyanghuiyu/chineseocr_lite#189]
![image](https://user-images.githubusercontent.com/28375774/86103803-ce574f80-baef-11ea-90f7-b932497ef4a3.png)
![image](https://user-images.githubusercontent.com/28375774/86103979-09598300-baf0-11ea-8e37-a94f7ff5b954.png)

**Comment by ouyanghuiyu** [comment]
@JohnnyZhang0628 目前效果不太好 我后续准备更新一下模型

**Comment by JohnnyZhang0628** [comment]
@ouyanghuiyu 好的，期待中。。。。
