### ISSUE TITLE
如何在自己的数据集上训练模型？

### ISSUE THREAD

**Issue by geyuxi** [ouyanghuiyu/chineseocr_lite#19]
作者您好，想问下如何使用自己的数据集（只包含字母和数字）去训练一个模型呢？我应该从哪里开始看呢？期待回复，谢谢

**Comment by ouyanghuiyu** [comment]
你好 文字识别我是用此项目中的代码训练的，改成了自己的网络结构 https://github.com/chineseocr/chineseocr/tree/master/train/ocr

**Comment by geyuxi** [comment]
> 你好 文字识别我是用此项目中的代码训练的，改成了自己的网络结构 https://github.com/chineseocr/chineseocr/tree/master/train/ocr

感谢回复
