### ISSUE TITLE
项目怎么没了呢，刚看到这个项目怎么是空的了

### ISSUE THREAD

**Issue by huye** [ouyanghuiyu/chineseocr_lite#197]
看了别人的演示效果还可以，准备下来看看，怎么仓库都强推了？我太难了。

**Comment by ouyanghuiyu** [comment]
@huye 不好意思 我准备加dbnet，操作不当导致的，正在修复中

**Comment by huye** [comment]
> @huye 不好意思 我准备加dbnet，操作不当导致的，正在修复中

不是吧，这个误操作有点吓人啊，强推不是有提示的吗

**Comment by ouyanghuiyu** [comment]
@huye 是的 好久没动这个代码了，以后注意
