### ISSUE TITLE
run.py error?

### ISSUE THREAD

**Issue by sporterman** [ouyanghuiyu/chineseocr_lite#2]
@ouyanghuiyu any suggestions?
![image](https://user-images.githubusercontent.com/13059352/75839010-9a4e7500-5e02-11ea-9ff3-a339b6d422c3.png)
environment ubuntu16.04  torch  1.12

**Comment by ouyanghuiyu** [comment]
This is already working, so you can predict on the web side

**Comment by sporterman** [comment]
@ouyanghuiyu     cannot open ip:8080 web
![image](https://user-images.githubusercontent.com/13059352/75839540-0087c780-5e04-11ea-8900-3b54068c4ac4.png)

**Comment by ouyanghuiyu** [comment]
add /ocr

**Comment by ouyanghuiyu** [comment]
add /ocr like  ip:8080/ocr

**Comment by sporterman** [comment]
much appreciate , it worked

![image](https://user-images.githubusercontent.com/13059352/75840911-6164cf00-5e07-11ea-84d0-ef6e94b67ecd.png)
