### ISSUE TITLE
dbnet ncnn实现

### ISSUE THREAD

**Issue by zhengqicl** [ouyanghuiyu/chineseocr_lite#206]
你好，我这边实现了ncnn dbnet，能否留个邮箱，我发个代码给你？

**Comment by ouyanghuiyu** [comment]
可以啊 要不你提交pr一下，我的邮箱760997646@qq.com

**Comment by zhengqicl** [comment]
> 可以啊 要不你提交pr一下，我的邮箱[760997646@qq.com](mailto:760997646@qq.com)

你好，代码已经发送到邮箱了

**Comment by ouyanghuiyu** [comment]
@zhengqicl 收到 感谢

**Comment by nihui** [comment]
奥利给！

**Comment by 2017ZYS** [comment]
@zhengqicl 感谢您的分享，请问您是怎么实现dbnet后面ncnn推断的概率图和阈值图的动态尺寸，如果直接通过onnx2ncnn转化的，最后输出尺寸应该是固定的，您是不是手动修改了Interp的 0为等比例缩放，修改1，2参数控制缩放比例，删除3，4实现的，我想确认一下

**Comment by zhengqicl** [comment]
> @zhengqicl 感谢您的分享，请问您是怎么实现dbnet后面ncnn推断的概率图和阈值图的动态尺寸，如果直接通过onnx2ncnn转化的，最后输出尺寸应该是固定的，您是不是手动修改了Interp的 0为等比例缩放，修改1，2参数控制缩放比例，删除3，4实现的，我想确认一下

我这边是直接使用作者的模型，通过https://convertmodel.com/?tdsourcetag=s_pctim_aiomsg这个网址直接转换的，不需要修改参数，原模型已经支持动态输入输出了。

**Comment by ouyanghuiyu** [comment]
@2017ZYS torch2ncnn 可以设置动态shape的

**Comment by 2017ZYS** [comment]
@ouyanghuiyu 是的，torch2onnx 是可以设置动态shape的，但使用onnxsimplifier需要指定input-shape,然受再转ncnn，param里的interp后面就是固定尺寸的缩放，Interp会有3，4参数固定尺寸缩放，然后我改了6个Interp参数，实现了尺寸的动态输出，按照@ zhengqicl 提供的代码也是能够正常推理的，结果也是对的。刚才我试了下，那个网站的直接转换出来后，是没有3，4参数，这是跟我的param的区别，可以直接推断，好用，感谢各位大佬。

**Comment by ouyanghuiyu** [comment]
@2017ZYS 嗯嗯 可以， 我还把最后的固定尺寸缩放删了，因为输入是32的倍数，最后尺寸是固定的，为了减少推理时间。
