### ISSUE TITLE
dbnet onnx model

### ISSUE THREAD

**Issue by amandazw** [ouyanghuiyu/chineseocr_lite#210]
我自己也处理一个dbnet的onnx模型，在python下使用onnxruntime加载成功了，但是C++调用结果有问题。所以想问有dbnet的onnx model有用C++配置onnxruntime加载成功过的大佬吗？

**Comment by jinfagang** [comment]
dbnet哪个版本？

**Comment by zhengqicl** [comment]
> 我自己也处理一个dbnet的onnx模型，在python下使用onnxruntime加载成功了，但是C++调用结果有问题。所以想问有dbnet的onnx model有用C++配置onnxruntime加载成功过的大佬吗？

我用作者官方模型调用成功

**Comment by amandazw** [comment]
> dbnet哪个版本？

paddleocr下的dbnet转onnx

**Comment by amandazw** [comment]
> > 我自己也处理一个dbnet的onnx模型，在python下使用onnxruntime加载成功了，但是C++调用结果有问题。所以想问有dbnet的onnx model有用C++配置onnxruntime加载成功过的大佬吗？
> 
> 我用作者官方模型调用成功

我也用作者的试试。最后那个输出output_tensor_不知道怎么取值出来。

**Comment by Ri-Yue-Shui-Hua** [comment]
> 我自己也处理一个dbnet的onnx模型，在python下使用onnxruntime加载成功了，但是C++调用结果有问题。所以想问有dbnet的onnx model有用C++配置onnxruntime加载成功过的大佬吗？

请教一下，dbnet转onnx模型是怎么支持变尺寸输入的？
