### ISSUE TITLE
mac下执行报错

### ISSUE THREAD

**Issue by yuhuofei** [ouyanghuiyu/chineseocr_lite#22]
find: -xtype: unknown primary or operator
make: `pse.so' is up to date.
device: cpu
load models
device: cpu
load models
device: cpu
load models
device: cpu
load model
Traceback (most recent call last):
  File "/Users/dane/anaconda3/lib/python3.7/site-packages/web/utils.py", line 526, in take
    yield next(seq)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 126, in <module>
    app = web.application(urls, globals())
  File "/Users/dane/anaconda3/lib/python3.7/site-packages/web/application.py", line 62, in __init__
    self.init_mapping(mapping)
  File "/Users/dane/anaconda3/lib/python3.7/site-packages/web/application.py", line 130, in init_mapping
    self.mapping = list(utils.group(mapping, 2))
  File "/Users/dane/anaconda3/lib/python3.7/site-packages/web/utils.py", line 531, in group
    x = list(take(seq, size))
RuntimeError: generator raised StopIteration

**Comment by yuhuofei** [comment]
Mac下执行有问题，编译pse.so的时候

find: -xtype: unknown primary or operator
c++ -o pse.so -I include  -std=c++11 -O3 -I/Users/dane/anaconda3/include/python3.7m -I/Users/dane/anaconda3/include/python3.7m -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/dane/anaconda3/include -arch x86_64 -I/Users/dane/anaconda3/include -arch x86_64 -L/Users/dane/anaconda3/lib/python3.7/config-3.7m-darwin -lpython3.7m -ldl -framework CoreFoundation pse.cpp --shared -fPIC
pse.cpp:32:29: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
        for (size_t i = 0; i<h; i++)
                           ~^~
pse.cpp:39:29: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
        for (size_t i = 0; i<h; i++)
                           ~^~
pse.cpp:42:32: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
            for(size_t j = 0; j<w; j++)
                              ~^~
3 warnings generated.

warning: (x86_64) /tmp/lto.o unable to open object file: No such file or directory

**Comment by ouyanghuiyu** [comment]
可能是 web.py 安装不对？

**Comment by yuhuofei** [comment]
> 可能是 web.py 安装不对？

pip list | grep web
sphinxcontrib-websupport           1.1.2
web.py                             0.40.dev0
webencodings                       0.5.1

**Comment by yuhuofei** [comment]
tks～

**Comment by BeHappyForMe** [comment]
> Mac下执行有问题，编译pse.so的时候
> 
> find: -xtype: unknown primary or operator
> c++ -o pse.so -I include -std=c++11 -O3 -I/Users/dane/anaconda3/include/python3.7m -I/Users/dane/anaconda3/include/python3.7m -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/dane/anaconda3/include -arch x86_64 -I/Users/dane/anaconda3/include -arch x86_64 -L/Users/dane/anaconda3/lib/python3.7/config-3.7m-darwin -lpython3.7m -ldl -framework CoreFoundation pse.cpp --shared -fPIC
> pse.cpp:32:29: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
> for (size_t i = 0; i<h; i++)
> ~^~
> pse.cpp:39:29: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
> for (size_t i = 0; i<h; i++)
> ~^~
> pse.cpp:42:32: warning: comparison of integers of different signs: 'size_t' (aka 'unsigned long') and 'int' [-Wsign-compare]
> for(size_t j = 0; j<w; j++)
> ~^~
> 3 warnings generated.
> 
> warning: (x86_64) /tmp/lto.o unable to open object file: No such file or directory

请问这个问题有解决了吗，我也碰到了
