### ISSUE TITLE
感觉没有旧版仓库里的好用啊

### ISSUE THREAD

**Issue by huye** [ouyanghuiyu/chineseocr_lite#220]
现在app.py的web直接报错不能用，flask_app.py这个可以，但是box的cx,cy和角度都为0了，并且识别低了很多，以前能识别的现在识别不了。就是现在别人fork里的旧仓库都有内存占用高的问题，能不能把别人fork那个拿回来处理呀。

https://github.com/ouyanghuiyu/chineseocr_lite/network/members

**Comment by ouyanghuiyu** [comment]
改一下config 里面检测模型配置就是旧版的了
