### ISSUE TITLE
识别结果不正确

### ISSUE THREAD

**Issue by yuhuofei** [ouyanghuiyu/chineseocr_lite#24]
![image](https://user-images.githubusercontent.com/316072/76375086-e314a980-637f-11ea-887a-ff1a2c10cc19.png)

你好，默认启动app后，识别算法怎么选择？
这个默认的结果感觉不正常～

**Comment by ouyanghuiyu** [comment]
上面的选项都不用选的，你这看着就没调用检测算法，耗时太低了

**Comment by yuhuofei** [comment]
![image](https://user-images.githubusercontent.com/316072/76388911-2cc3bb00-63a5-11ea-81c8-02292d79701f.png)

关键上面选项不选的化，直接就core了～

**Comment by ouyanghuiyu** [comment]
你重新拉下代码跑跑看

**Comment by yuhuofei** [comment]
> 你重新拉下代码跑跑看

拉了一份新代码，结果还是一样的
不选择上面那几个选项，直接就core了
选择后只识别出一个字～
