### ISSUE TITLE
train file

### ISSUE THREAD

**Issue by an1018** [ouyanghuiyu/chineseocr_lite#25]
@ouyanghuiyu 你好
1）请问三个模型的训练文件什么时候会开源
2）将模型转为ncnn库模型，再训练吗，这样做的目的是什么

**Comment by ouyanghuiyu** [comment]
你好
1) 训练代码在redame的github链接可以找到，角度检测的是简单的分类模型。  后续有时间可以整理一下开源出来
2）ncnn是方便边缘设备（手机端）推理，模型不用重新训练的

**Comment by an1018** [comment]
@ouyanghuiyu 非常感谢回复~还有一些问题向您请教：
文字检测用的什么数据集呢
角度检测是需要生成四个方向的文本图片吗，图片大小多少？
识别训练集每张图片文字是固定数量，还是小于多少个，图片大小多少？

**Comment by ouyanghuiyu** [comment]
> @ouyanghuiyu 非常感谢回复~还有一些问题向您请教：
> 文字检测用的什么数据集呢
> 角度检测是需要生成四个方向的文本图片吗，图片大小多少？
> 识别训练集每张图片文字是固定数量，还是小于多少个，图片大小多少？

1、文字检测：https://tianchi.aliyun.com/competition/entrance/231651/introduction
2、角度是自己生成的，大概总共20w的图片吧
3、识别生成的图片是固定文字，自己的数据集不是固定的，大概300w张吧

**Comment by an1018** [comment]
明白了，多谢

**Comment by gittigxuy** [comment]
@an1018 @ouyanghuiyu 请问一下训练代码在哪里呢？这个项目只给了一个demo吧？作者的意思是让我们从psenet和crnn里面的训练代码进行修改吗？
