### ISSUE TITLE
为什么crnn 的ncnn推理要分段进行？

### ISSUE THREAD

**Issue by sporterman** [ouyanghuiyu/chineseocr_lite#250]
![image](https://user-images.githubusercontent.com/13059352/92855888-63968e80-f425-11ea-9373-914d845859b7.png)

@ouyanghuiyu  你好  请问为什么这里的ncnn 推理crnn的部分  分成了几个阶段  包括 从开始到234，   从253到254，   260到387，  406到407,
是因为ncnn不支持reshape操作吗？

**Comment by sporterman** [comment]
目前ncnn是否支持crnn一步直接推理结果

**Comment by allanruin** [comment]
ncnn不支持batch的概念。但CRNN模型中有InnerProduct操作，必须要用到batch。所以这里只能部分加载模型，然后用代码里的for循环取替代实现带batch的InnerProduct。

**Comment by allanruin** [comment]
另外你也在试图重新训练一个自己的NCNN模型吗？可以加好友交流

**Comment by sporterman** [comment]
> 另外你也在试图重新训练一个自己的NCNN模型吗？可以加好友交流

可以啊  刚好我也在学习， 我微信号  13533297722
