### ISSUE TITLE
训练集问题

### ISSUE THREAD

**Issue by tianyazhe233** [ouyanghuiyu/chineseocr_lite#28]
您好，是否方便提供少量的竖排训练集的样例呢？

**Comment by ouyanghuiyu** [comment]
你好，后续我提供一部分样本以及生成竖排样本的字体

**Comment by ouyanghuiyu** [comment]
> 您好，是否方便提供少量的竖排训练集的样例呢？

已经提供了 详细看readme

**Comment by ouyanghuiyu** [comment]
> 您好，是否方便提供少量的竖排训练集的样例呢？

已经提供了 详细看readme

**Comment by tianyazhe233** [comment]
> > 您好，是否方便提供少量的竖排训练集的样例呢？
> 
> 已经提供了 详细看readme
看到了，多谢
