### ISSUE TITLE
楼主好，我看您的模型效果很好，请问是用的什么数据集训练的？

### ISSUE THREAD

**Issue by fendaq** [ouyanghuiyu/chineseocr_lite#3]
楼主好，我看您的模型效果很好，请问是用的什么数据集训练的？

**Comment by ouyanghuiyu** [comment]
你自己测过了吗，我感觉效果不是特别好 哈哈

**Comment by wangbingok1118** [comment]
> 楼主好，我看您的模型效果很好，请问是用的什么数据集训练的？

+1

**Comment by ouyanghuiyu** [comment]
> +1

crnn 横排 我主要是https://github.com/YCG09/chinese_ocr 提到的数据集和自己的一些生成的数据集，竖排我主要是用生成的数据集

**Comment by piaobuliao** [comment]
这个效果很赞啊 艺术字都能识别这么好，这个样本怎么造？

**Comment by ouyanghuiyu** [comment]
> 识别结果展示的图片是在训练集里的图片吗？
> 这个艺术字都能识别这么好，效果很赞啊 ，这个样本怎么造？

没有在训练集的，我是基于这个项目https://github.com/Sanster/text_renderer 和 https://github.com/yanhaiming56/SynthText_Chinese_py3生成的，当然自己也收集了许多数据集。 效果其实不太好，你可以自己试试其他图片

**Comment by Excalibur0214** [comment]
首先感谢您的模型分享
我想问问您是用什么方法进行数据生成的呢，我之前也试过用生成的数据做票据识别，但即使肉眼看上去很相似的数据，最后训练出来的识别模型效果依然很差

**Comment by ouyanghuiyu** [comment]
> 首先感谢您的模型分享
> 我想问问您是用什么方法进行数据生成的呢，我之前也试过用生成的数据做票据识别，但即使肉眼看上去很相似的数据，最后训练出来的识别模型效果依然很差

用一部分真实的数据集呢

**Comment by Excalibur0214** [comment]
> > 首先感谢您的模型分享
> > 我想问问您是用什么方法进行数据生成的呢，我之前也试过用生成的数据做票据识别，但即使肉眼看上去很相似的数据，最后训练出来的识别模型效果依然很差
> 
> 用一部分真实的数据集呢

您好，可否大概透露一下生成数据与真实数据的比例呢，我猜应该是用生成的数据训练再用真实数据finetune，但汉字那么多用少量数据finetune（比如说真实数据甚至不能覆盖字典中的所有字）会有提升吗

**Comment by learn01one** [comment]
楼主你好，你是对竖排和横排混合着训练的吗，还是有其它训练策略，可否提供一些思路，谢谢

**Comment by ouyanghuiyu** [comment]
> 楼主你好，你是对竖排和横排混合着训练的吗，还是有其它训练策略，可否提供一些思路，谢谢

你好，竖排和横排我是分开训练的，竖排主要是用90度的字体进行生成的样本

**Comment by yangsuhui** [comment]
楼主，您好，请问竖排是用90度的字体进行生成的样本怎么理解？
是用https://github.com/Sanster/text_renderer或者https://github.com/yanhaiming56/SynthText_Chinese_py3项目生成的吗？
但是这两个项目生成的是水平文本，怎么设置字体是90°的？
谢谢

**Comment by ouyanghuiyu** [comment]
> 楼主，您好，请问竖排是用90度的字体进行生成的样本怎么理解？
> 是用[https://github.com/Sanster/text_renderer或者https://github.com/yanhaiming56/SynthText_Chinese_py3项目生成的吗？](https://github.com/Sanster/text_renderer%E6%88%96%E8%80%85https://github.com/yanhaiming56/SynthText_Chinese_py3%E9%A1%B9%E7%9B%AE%E7%94%9F%E6%88%90%E7%9A%84%E5%90%97%EF%BC%9F)
> 但是这两个项目生成的是水平文本，怎么设置字体是90°的？
> 谢谢

在readme已经说明了 也提供了相应字体在https://github.com/ouyanghuiyu/chineseocr_lite/tree/master/vertical_text_fonts/fonts

**Comment by yunxintryyoubest** [comment]
@ouyanghuiyu  楼主，您好，哪里有提供这个项目训练部分的代码？

**Comment by yunxintryyoubest** [comment]
@ouyanghuiyu  楼主，您好，哪里有提供这个项目训练部分的代码？
