### ISSUE TITLE
识别不准确

### ISSUE THREAD

**Issue by tomatoren** [ouyanghuiyu/chineseocr_lite#30]
你好 我编译app.py时也出现了很多包缺失 web numpy cv2 等 后面都install跑起来了 但是感觉不是特别准确 不知道是不是哪里操作问题
![ocr](https://user-images.githubusercontent.com/35512338/76489653-f8630400-6463-11ea-963e-baf73441a352.png)

**Comment by ouyanghuiyu** [comment]
> 你好 我编译app.py时也出现了很多包缺失 web numpy cv2 等 后面都install跑起来了 但是感觉不是特别准确 不知道是不是哪里操作问题
> ![ocr](https://user-images.githubusercontent.com/35512338/76489653-f8630400-6463-11ea-963e-baf73441a352.png)

提供一下原图片吗，我截图后识别感觉还可以

**Comment by tomatoren** [comment]
> > 你好 我编译app.py时也出现了很多包缺失 web numpy cv2 等 后面都install跑起来了 但是感觉不是特别准确 不知道是不是哪里操作问题
> > ![ocr](https://user-images.githubusercontent.com/35512338/76489653-f8630400-6463-11ea-963e-baf73441a352.png)
> 
> 提供一下原图片吗，我截图后识别感觉还可以

![1116后结算项目任务](https://user-images.githubusercontent.com/35512338/76492953-67445b00-646c-11ea-9a6f-fa4261da37ed.png)

**Comment by ouyanghuiyu** [comment]
> > > 你好 我编译app.py时也出现了很多包缺失 web numpy cv2 等 后面都install跑起来了 但是感觉不是特别准确 不知道是不是哪里操作问题
> > > ![ocr](https://user-images.githubusercontent.com/35512338/76489653-f8630400-6463-11ea-963e-baf73441a352.png)
> > 
> > 
> > 提供一下原图片吗，我截图后识别感觉还可以
> 
> ![1116后结算项目任务](https://user-images.githubusercontent.com/35512338/76492953-67445b00-646c-11ea-9a6f-fa4261da37ed.png)

![image](https://user-images.githubusercontent.com/42023607/76504091-fc9e1a00-6481-11ea-9ffa-197ae0f09fb2.png)
我测了一下 也不是很准 ，但比你的要好些，你重新拉下代码看看

**Comment by ouyanghuiyu** [comment]
![image](https://user-images.githubusercontent.com/42023607/76504251-4f77d180-6482-11ea-8a55-84bc2271f601.png)
我测了一下 比你的要好一些，你重新拉下代码看看

**Comment by ouyanghuiyu** [comment]
> ![image](https://user-images.githubusercontent.com/42023607/76504251-4f77d180-6482-11ea-8a55-84bc2271f601.png)
> 我测了一下 比你的要好一些，你重新拉下代码看看

我push了一个最近训练精度较高的版本crnn_lite_lstm_dw_v2，你可以pull一下
