### ISSUE TITLE
训练集大小以及时间

### ISSUE THREAD

**Issue by lllfx** [ouyanghuiyu/chineseocr_lite#31]
你好，请问你用了多少数据集，训练了多久。

**Comment by ouyanghuiyu** [comment]
检测1w张 识别300w张把 角度20w张

**Comment by dyning** [comment]
@ouyanghuiyu ，请问下这些数据是开源数据，还是你们个人数据？

**Comment by ouyanghuiyu** [comment]
> @ouyanghuiyu ，请问下这些数据是开源数据，还是你们个人数据？

开源以及合成的

**Comment by lllfx** [comment]
> 检测1w张 识别300w张把 角度20w张

非常感谢回复。  请问你这边用的什么型号GPU训练的，需要训练多久？

**Comment by dyning** [comment]
@ouyanghuiyu 谢谢回复
