### ISSUE TITLE
使用OcrLiteOnnxJvm.jar如何关闭控制台打印的消息？

### ISSUE THREAD

**Issue by dzcdhj** [ouyanghuiyu/chineseocr_lite#328]
使用OcrLiteOnnxJvm.jar，如何不打印控制台消息？

numThread=8
modelsDir=c:/OcrLiteOnnx/models
det=dbnet.onnx
。。。

**Comment by benjaminwan** [comment]
[Main.java](https://github.com/DayBreak-u/chineseocr_lite/blob/onnx/jvm_projects/OcrLiteOnnxJvm/src/main/java/com/benjaminwan/ocr/Main.java)
//关闭各种log
ocrEngine.initLogger(
                false,
                false,
                false
        );
//关闭生成resulttext
//ocrEngine.enableResultText(imagePath);

**Comment by dzcdhj** [comment]
> 
> 
> [Main.java](https://github.com/DayBreak-u/chineseocr_lite/blob/onnx/jvm_projects/OcrLiteOnnxJvm/src/main/java/com/benjaminwan/ocr/Main.java)
> //关闭各种log
> ocrEngine.initLogger(
> false,
> false,
> false
> );
> //关闭生成resulttext
> //ocrEngine.enableResultText(imagePath);

三个配置全部设置成false了，仍然在打印这些信息！关不了log！

**Comment by benjaminwan** [comment]
范例demo是kotlin的，如果你是用kotlin，要改这个文件[main.kt](https://github.com/DayBreak-u/chineseocr_lite/blob/onnx/jvm_projects/OcrLiteOnnxJvm/src/main/java/com/benjaminwan/ocr/main.kt)

**Comment by dzcdhj** [comment]
> demo是kotlin的，如果你是用kotlin

直接下载的OcrLiteOnnxJvm.jar，如何修改main.kt？
文件在哪里？
用的这个文件中的jar包：OcrLiteOnnxJvm-v1.5.1.20210128.7z

**Comment by benjaminwan** [comment]
OcrLiteOnnxJvm.jar仅是简单范例，只是用于基本的测试，不适合直接使用。
最好把代码集成到自己的项目里。
代码就如 这个链接里的 https://github.com/DayBreak-u/chineseocr_lite/blob/onnx/jvm_projects/OcrLiteOnnxJvm/src/main/java/com/benjaminwan/ocr/main.kt

**Comment by dzcdhj** [comment]
> 
> 
> OcrLiteOnnxJvm.jar仅是简单范例，只是用于基本的测试，不适合直接使用。
> 最好把代码集成到自己的项目里。
> 代码就如 这个链接里的 https://github.com/DayBreak-u/chineseocr_lite/blob/onnx/jvm_projects/OcrLiteOnnxJvm/src/main/java/com/benjaminwan/ocr/main.kt

源码从上面链接下载放项目里，取消OcrLiteOnnxJvm.jar的依赖，main.kt报错，咋调整呢？

**Comment by benjaminwan** [comment]
main.kt是kotlin代码，需要kotlin语言标准库。
如果你的工程里没有kotlin代码，就用java版:https://github.com/DayBreak-u/chineseocr_lite/blob/onnx/jvm_projects/OcrLiteOnnxJvm/src/main/java/com/benjaminwan/ocr/Main.java

**Comment by dzcdhj** [comment]
> 
> 
> main.kt是kotlin代码，需要kotlin语言标准库。
> 如果你的工程里没有kotlin代码，就用java版:https://github.com/DayBreak-u/chineseocr_lite/blob/onnx/jvm_projects/OcrLiteOnnxJvm/src/main/java/com/benjaminwan/ocr/Main.java

我是用的java版，你建议不用demo直接用源码，请问源码在哪里下载呢？谢谢！

QQ群里朋友找到了日志信息来源，是OcrLiteJni.cpp 文件中使用printf 打印的，希望demo中的dll文件重新生成一下，把这些printf也加入日志控制或者直接删除。同时看看Linux版本是否也有这些打印信息。

**Comment by benjaminwan** [comment]
先介绍下项目的结构：
这个项目有2个分支，master和onnx。
其中master分支的代码和模型是老的版本，已经废弃，请不要使用。
但是Git会在同步或者github在下载代码时，默认还是以master分支来操作的。
所以没有搞清楚这点的话，默认下载下来的东西就是废弃的master分支代码。

**Comment by benjaminwan** [comment]
onnx分支分为2种模型：原始onnx模型和ncnn模型。
这2种模型实现的功能是一样的，只不过onnx模型是用onnxruntime框架来调用，ncnn模型则是用ncnn框架来调用。
开始之前，先确定你要使用哪种框架，来选择哪种模型。

**Comment by benjaminwan** [comment]
选好了模型和框架，接下来就看你需要哪种语言的demo。
项目根目录:onnx python demo，这也是作者开发的版本。
android_projects目录：放了onnx和ncnn两种版本的android demo
cpp_projects目录：放了onnx和ncnn两种版本的C++demo，可用于win/linux/mac
jvm_projects目录：放了onnx和ncnn两种版本的Java和kotlin demo，可用于win/linux/mac
dotnet_projects目录：放了onnx的C#和VB.net Demo。
这些demo根据需要选择1种即可。

**Comment by benjaminwan** [comment]
那么你需要的java demo：https://github.com/DayBreak-u/chineseocr_lite/tree/onnx/jvm_projects
里面有2个文件夹，每个点进去，都可以查看到详细的jvm编译说明。
java版demo是通过jni调用对应版本的动态运行库，所以java代码很少，主要的代码都在C++项目里。
也就是说java版要运行起来，还必须把对应的C++项目编译成.dll或.so，让java调用才行。
所以jvm编译说明也提到了 “开始JVM部分编译之前，请先完成编译xxxx动态运行库，参考此页面的编译说明。”

**Comment by benjaminwan** [comment]
所以jvm项目的全部代码包括：jvm_projects + cpp_projects
群共享里有整合好依赖库的压缩包，找以project_开头的压缩包即可。
C++项目解压后大概不到2GB。

**Comment by dzcdhj** [comment]
> 所以jvm项目的全部代码包括：jvm_projects + cpp_projects
> 群共享里有整合好依赖库的压缩包，找以project_开头的压缩包即可。
> C++项目解压后大概不到2GB。

非常感谢这么详细的说明！！
