### ISSUE TITLE
关于CPU环境下64位与32位C++ ONNX 内存占用问题

### ISSUE THREAD

**Issue by yjmm10** [ouyanghuiyu/chineseocr_lite#343]
测试环境：windows10 64位  vs2019 c++onnx版本

64位，内存占用在300M以上
32位，内存占用在100M以内
同样的环境为何差异这么大，跟哪些因素有关呢？

**Comment by benjaminwan** [comment]
ubuntu x64 1线程 内存占用峰值图给你参考，1线程需要约峰值1GB内存。
![截屏2021-03-31 上午9 52 46](https://user-images.githubusercontent.com/2362051/118351449-af8a6c00-b58e-11eb-8371-80a9f240cda3.png)
