### ISSUE TITLE
python3.7 编译的无法执行

### ISSUE THREAD

**Issue by ht-dep** [ouyanghuiyu/chineseocr_lite#35]
from .pse import pse_cpp
ImportError: Python version mismatch: module was compiled for Python 3.6, but the interpreter version is incompatible: 3.7.1 (default, Dec 18 2019, 23:13:02)

**Comment by Caesarthegreat** [comment]
i also hit this issue, should i degrade Python ??

**Comment by ht-dep** [comment]
同样，还不支持 （don't support）centos

> i also hit this issue, should i degrade Python ??

**Comment by Caesarthegreat** [comment]
在昨天作者的3.12版本没提之前，都没有报过这个错啊

**Comment by ht-dep** [comment]
> 在昨天作者的3.12版本没提之前，都没有报过这个错啊

刚发现要求的最低gcc是4.9，centos的yum 默认的最新是4.8，把gcc升级后py36是可以用的. 我再试试py3.7编译试下效果。

**Comment by ht-dep** [comment]
> i also hit this issue, should i degrade Python ??

升级下（update）gcc试试，yum默认（default）的是4.8，这个是要求最低4.9的。

**Comment by Caesarthegreat** [comment]
> 同样，还不支持 （don't support）centos
> 
> > i also hit this issue, should i degrade Python ??



> gcc

小哥哥，我的GCC是7.3.0 。。。。。。。

**Comment by ht-dep** [comment]
> > 同样，还不支持 （don't support）centos
> > > i also hit this issue, should i degrade Python ??
> 
> > gcc
> 
> 小哥哥，我的GCC是7.3.0 。。。。。。。

还以为外国友人。 结果假冒伪劣  。 有没有 yum install python3-devel。 我刚在py36 +gcc8下测了没问题。晚上回去我再试试py37

**Comment by Caesarthegreat** [comment]
> ?



> > > 同样，还不支持 （don't support）centos
> > > > i also hit this issue, should i degrade Python ??
> > 
> > 
> > > gcc
> > 
> > 
> > 小哥哥，我的GCC是7.3.0 。。。。。。。
> 
> 还以为外国友人。 结果假冒伪劣 。 有没有 yum install python3-devel。 我刚在py36 +gcc8下测了没问题。晚上回去我再试试py37

被你识破了。。。那句英语是装了一下逼。。。我是刚用github， 想试试蹩脚英语的快感。。
yum install python3-devel 我原来已经执行过了，现在是最新版本

**Comment by ht-dep** [comment]
> > ?
> 
> > > > 同样，还不支持 （don't support）centos
> > > > > i also hit this issue, should i degrade Python ??
> > > 
> > > 
> > > > gcc
> > > 
> > > 
> > > 小哥哥，我的GCC是7.3.0 。。。。。。。
> > 
> > 
> > 还以为外国友人。 结果假冒伪劣 。 有没有 yum install python3-devel。 我刚在py36 +gcc8下测了没问题。晚上回去我再试试py37
> 
> 被你识破了。。。那句英语是装了一下逼。。。我是刚用github， 想试试蹩脚英语的快感。。
> yum install python3-devel 我原来已经执行过了，现在是最新版本

已经测试，centos7  +py37 +gcc8  ,先删掉pse.so 再make，再运行没毛病。不要管作者的那个requirement（这个有点问题）

**Comment by Caesarthegreat** [comment]
> > > ?
> > 
> > 
> > > > > 同样，还不支持 （don't support）centos
> > > > > > i also hit this issue, should i degrade Python ??
> > > > 
> > > > 
> > > > > gcc
> > > > 
> > > > 
> > > > 小哥哥，我的GCC是7.3.0 。。。。。。。
> > > 
> > > 
> > > 还以为外国友人。 结果假冒伪劣 。 有没有 yum install python3-devel。 我刚在py36 +gcc8下测了没问题。晚上回去我再试试py37
> > 
> > 
> > 被你识破了。。。那句英语是装了一下逼。。。我是刚用github， 想试试蹩脚英语的快感。。
> > yum install python3-devel 我原来已经执行过了，现在是最新版本
> 
> 已经测试，centos7 +py37 +gcc8 ,先删掉pse.so 再make，再运行没毛病。不要管作者的那个requirement（这个有点问题）

小哥哥，你说的运行没毛病是什么意思？它的web界面上有5个滚动按钮，你都试了么？有么有问题？

**Comment by ht-dep** [comment]
> > > > ?
> > > 
> > > 
> > > > > > 同样，还不支持 （don't support）centos
> > > > > > > i also hit this issue, should i degrade Python ??
> > > > > 
> > > > > 
> > > > > > gcc
> > > > > 
> > > > > 
> > > > > 小哥哥，我的GCC是7.3.0 。。。。。。。
> > > > 
> > > > 
> > > > 还以为外国友人。 结果假冒伪劣 。 有没有 yum install python3-devel。 我刚在py36 +gcc8下测了没问题。晚上回去我再试试py37
> > > 
> > > 
> > > 被你识破了。。。那句英语是装了一下逼。。。我是刚用github， 想试试蹩脚英语的快感。。
> > > yum install python3-devel 我原来已经执行过了，现在是最新版本
> > 
> > 
> > 已经测试，centos7 +py37 +gcc8 ,先删掉pse.so 再make，再运行没毛病。不要管作者的那个requirement（这个有点问题）
> 
> 小哥哥，你说的运行没毛病是什么意思？它的web界面上有5个滚动按钮，你都试了么？有么有问题？

没试，只用了检测识别。单行检测就是只调用文字识别，通用是就检测+识别，身份证和火车票只不过是对通用的数据做了层组装。  author写的这个web，有点乱。 
`[root@192 chineseocr_psnet]# python3 test.py
make: 进入目录“/home/Code/chineseocr_psnet/psenet/pse”
make: “pse.so”是最新的。
make: 离开目录“/home/Code/chineseocr_psnet/psenet/pse”
device: cpu
load models
device: cpu
load models
device: cpu
load models
device: cpu
load model
[{'cx': 423.55833333333334, 'cy': 47.74479166666667, 'text': 'PyTorch是使用GPU和CPU优化的深度学习张量库。', 'w': 863.0, 'h': 68.0, 'degree': -0.0}]
`

**Comment by ht-dep** [comment]
发现 更新gcc后，自动给我安装了py36

**Comment by Caesarthegreat** [comment]
author又更新了，down下来试试
我的情况是：识别简单图片可以，但身份证就直接报错了。。。奇怪。。。

**Comment by ouyanghuiyu** [comment]
这个web是我直接用chineseocr的，我自己对web不熟悉，请求大佬奉献web代码

**Comment by ht-dep** [comment]
893216718@qq.com 加qq聊吧，我把这个 关了哈

**Comment by Caesarthegreat** [comment]
那你们聊吧，有结果了告诉我哦，小哥哥们。。。

**Comment by ouyanghuiyu** [comment]
> [893216718@qq.com](mailto:893216718@qq.com) 加qq聊吧，我把这个 关了哈

已加

**Comment by ht-dep** [comment]
我还以为是Caesarthegreat，没想到是author ，哈哈

**Comment by ht-dep** [comment]
> > [893216718@qq.com](mailto:893216718@qq.com) 加qq聊吧，我把这个 关了哈
> 
> 已加

发个msg，我给整一个flask版本的吧

**Comment by Caesarthegreat** [comment]
> > > [893216718@qq.com](mailto:893216718@qq.com) 加qq聊吧，我把这个 关了哈
> > 
> > 
> > 已加
> 
> 发个msg，我给整一个flask版本的吧

你们聊的怎么样？  身份证能识别么？

**Comment by ht-dep** [comment]
> > [893216718@qq.com](mailto:893216718@qq.com) 加qq聊吧，我把这个 关了哈
> 
> 已加

可能加错了吧，893216718

**Comment by ouyanghuiyu** [comment]
> > > [893216718@qq.com](mailto:893216718@qq.com) 加qq聊吧，我把这个 关了哈
> > 
> > 
> > 已加
> 
> 可能加错了吧，893216718

昵称Q.hongtao 是你吗

**Comment by ouyanghuiyu** [comment]
> > > [893216718@qq.com](mailto:893216718@qq.com) 加qq聊吧，我把这个 关了哈
> > 
> > 
> > 已加
> 
> 可能加错了吧，893216718

![image](https://user-images.githubusercontent.com/42023607/76720975-687dcc80-6779-11ea-9b1f-b8506b1428a8.png)
