### ISSUE TITLE
为什么模型中文识别不准确啊

### ISSUE THREAD

**Issue by Tony1236** [ouyanghuiyu/chineseocr_lite#37]
你好，最开始通用OCR识别还是很准确的，后来你更新代码后就不准确了，还有就是火车票和身份证识别一直不准确啊，现在的识别结果如下：
![test1](https://user-images.githubusercontent.com/53893913/76604930-916c4a80-654a-11ea-9936-6f75e9c92b0d.png)

**Comment by ouyanghuiyu** [comment]
您好，我更新后吧long_size变大了，检测这些大字可能不太好，在config里面配置一下 pse_long_size改小点，身份证和火车票识别，web端代码有bug，我对这一块是不是很熟悉，还不知道错在哪

**Comment by ht-dep** [comment]
> 您好，我更新后吧long_size变大了，检测这些大字可能不太好，在config里面配置一下 pse_long_size改小点，身份证和火车票识别，web端代码有bug，我对这一块是不是很熟悉，还不知道错在哪

requement.py 建议把web.py版本改为web.py==0.40.

**Comment by Tony1236** [comment]
已经正常了，谢谢！这个通用OCR可用于车牌识别吗

**Comment by ht-dep** [comment]
最好根据你的场景再训练下吧

> 已经正常了，谢谢！这个通用OCR可用于车牌识别吗
