### ISSUE TITLE
MAC上面编译报错

### ISSUE THREAD

**Issue by zhh8689** [ouyanghuiyu/chineseocr_lite#373]
CMake Error at CMakeLists.txt:57 (find_package):
  By not providing "FindOnnxRuntime.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "OnnxRuntime", but CMake did not find one.

  Could not find a package configuration file provided by "OnnxRuntime" with
  any of the following names:

    OnnxRuntimeConfig.cmake
    onnxruntime-config.cmake

  Add the installation prefix of "OnnxRuntime" to CMAKE_PREFIX_PATH or set
  "OnnxRuntime_DIR" to a directory containing one of the above files.  If
  "OnnxRuntime" provides a separate development package or SDK, be sure it
  has been installed.

cmake的版本跟openMP的版本都正确。求教怎么处理
<img width="1092" alt="image" src="https://user-images.githubusercontent.com/3362757/131776927-506d0631-9fd0-4b43-a4d2-2274c7c8ea43.png">

**Comment by MistEO** [comment]
我也遇到了同样的问题，https://github.com/DayBreak-u/chineseocr_lite/issues/366#issuecomment-894703826

换onnx-1.6那个库，1.7的目录结构不对

**Comment by zhh8689** [comment]
> 我也遇到了同样的问题，[#366 (comment)](https://github.com/DayBreak-u/chineseocr_lite/issues/366#issuecomment-894703826)
> 
> 换onnx-1.6那个库，1.7的目录结构不对

换成1.6确实可以编译了
