### ISSUE TITLE
web服务运行几分钟后进程被killed

### ISSUE THREAD

**Issue by kidchild1985** [ouyanghuiyu/chineseocr_lite#38]
跟下面一个说的一样，会经常被killed。 个人感觉这个会严重影响这个开源项目的质量。

**Comment by ouyanghuiyu** [comment]
是不是你的配置内存太小的原因，可以把config里面 pse_long_size 改小点看看

**Comment by ouyanghuiyu** [comment]
> 跟下面一个说的一样，会经常被killed。 个人感觉这个会严重影响这个开源项目的质量。

确实是有内存泄露的情况

**Comment by ouyanghuiyu** [comment]
> 跟下面一个说的一样，会经常被killed。 个人感觉这个会严重影响这个开源项目的质量。

确实有内存泄露的情况，我排查一下

**Comment by ouyanghuiyu** [comment]
> 跟下面一个说的一样，会经常被killed。 个人感觉这个会严重影响这个开源项目的质量。

是web框架的内存泄露问题，我直接循环调用model.py里面的函数，并不会出现内存一直增长
if __name__ == "__main__":
    import random
    while 1:
        imgpath = "./test_imgs/{}.jpg".format(random.choice([1,2,3,4,5]))
        img = cv2.imread(imgpath)
        result  =    text_predict(img)

**Comment by ws160920096** [comment]
你好，请问对于kill问题，怎么修改可以解决呢（我没懂之前得解释）

**Comment by ouyanghuiyu** [comment]
> 你好，请问对于kill问题，怎么修改可以解决呢（我没懂之前得解释）

我觉得真的需要搭建web服务，可以自己搭一个，模型推理部分是没有内存问题的，我不太懂前端

**Comment by ws160920096** [comment]
好的，谢谢

------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"ouyanghuiyu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月16日(星期一) 晚上7:44
收件人:&nbsp;"ouyanghuiyu/chineseocr_lite"<chineseocr_lite@noreply.github.com&gt;;
抄送:&nbsp;"sunandstar"<2522107407@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ouyanghuiyu/chineseocr_lite] web服务运行几分钟后进程被killed (#38)





  
你好，请问对于kill问题，怎么修改可以解决呢（我没懂之前得解释）
  
我觉得真的需要搭建web服务，可以自己搭一个，模型推理部分是没有内存问题的，我不太懂前端

**Comment by ChenjieXu** [comment]
> > 你好，请问对于kill问题，怎么修改可以解决呢（我没懂之前得解释）
> 
> 我觉得真的需要搭建web服务，可以自己搭一个，模型推理部分是没有内存问题的，我不太懂前端

你试一下使用不同图片的预测，我用while循环预测同一张没有内存泄露，但是不同图片的不行。
