### ISSUE TITLE
vs编译执行脚本文件乱码

### ISSUE THREAD

**Issue by husiluanxiang** [ouyanghuiyu/chineseocr_lite#382]
你好！我按照Ncnn的编译说明，编译失败，请问这是什么导致，环境问题吗？？
        PS D:\OCR\chineseocr_lite-onnx\cpp_projects\OcrLiteNcnn> .\generate-vs-project.bat
'悄孕斜嘁隓ebug版的Ncnn和Opencv，否则请不要选择Debug编译"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'D_TYPE' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'"CPU")Error!")' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
"请选择编译输出类型并回车: 1)编译成可执行文件，2)编译成JNI动态库，3)编译成C动态库"
'EXE"' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'lag' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'请输入选项并回车:' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'p' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'lagbuildALL)if' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
PS D:\OCR\chineseocr_lite-onnx\cpp_projects\OcrLiteNcnn>

**Comment by benjaminwan** [comment]
Windows7执行错误|中文乱码
1.cmd窗口左上角-属性
2.字体选项卡-选择除了“点阵字体”以外的TrueType字体,例如:Lucida Console、宋体
3.重新执行bat

**Comment by husiluanxiang** [comment]
> Windows7执行错误|中文乱码 1.cmd窗口左上角-属性 2.字体选项卡-选择除了“点阵字体”以外的TrueType字体,例如:Lucida Console、宋体 3.重新执行bat

我是win10的系统，按照这上面的修改是还是乱码，无法执行

**Comment by benjaminwan** [comment]
generate-vs-project.bat这个文件如果是从git仓库检出的，会是linux格式的，需要转成windows格式。
用notepad++打开，菜单"编辑"-"文档格式转换"-"转换为windows格式"
如果不懂得操作，进qq群的共享下载打包好的project工程源代码。

**Comment by cqray1990** [comment]
@benjaminwan  我用的minGW64 编译的opencv:


:: build opencv 3.4.x for windows by benjaminwan
@ECHO OFF
chcp 65001
cls
@SETLOCAL

echo 请选择生成库选项并回车: 1)Shared动态库，2)Static静态库:
echo Please Select Lib Type: 1)Shared Lib，2)Static Lib:
set BUILD_SHARED=ON
set /p flag=
if %flag% == "" (set BUILD_SHARED=ON)^
else if %flag% == 1 (set BUILD_SHARED=ON)^
else if %flag% == 2 (set BUILD_SHARED=OFF)^
else (echo "输入错误！Input Error!")

echo 请选择要生成的选项并回车: 0)ALL，1)VS2015-x86，2)VS2015-x64，3)VS2017-x86，4)VS2017-x64，5)VS2019-x86，6)VS2019-x64，7)MinGW:
echo Please Select VS Ver: 0)ALL，1)VS2015-x86，2)VS2015-x64，3)VS2017-x86，4)VS2017-x64，5)VS2019-x86，6)VS2019-x64，7)MinGW:
set /p flag=
if %flag% == 0 (call :buildALL)^
else if %flag% == 1 (call :build2015x86)^
else if %flag% == 2 (call :build2015x64)^
else if %flag% == 3 (call :build2017x86)^
else if %flag% == 4 (call :build2017x64)^
else if %flag% == 5 (call :build2019x86)^
else if %flag% == 6 (call :build2019x64)^
else if %flag% == 7 (call :buildMinGW)^
else (echo "输入错误！Input Error!")
GOTO:EOF

:buildALL
call :build2015x86
call :build2015x64
call :build2017x86
call :build2017x64
call :build2019x86
call :build2019x64
call :buildMinGW
GOTO:EOF

:build2015x86
mkdir build-win-vs2015-x86
pushd build-win-vs2015-x86
call :cmakeParams "Visual Studio 14 2015" "Win32"
popd
GOTO:EOF

:build2015x64
mkdir build-win-vs2015-x64
pushd build-win-vs2015-x64
call :cmakeParams "Visual Studio 14 2015" "x64"
popd
GOTO:EOF

:build2017x86
mkdir build-win-vs2017-x86
pushd build-win-vs2017-x86
call :cmakeParams "Visual Studio 15 2017" "Win32"
popd
GOTO:EOF

:build2017x64
mkdir build-win-vs2017-x64
pushd build-win-vs2017-x64
call :cmakeParams "Visual Studio 15 2017" "x64"
popd
GOTO:EOF

:build2019x86
mkdir build-win-vs2019-x86
pushd build-win-vs2019-x86
call :cmakeParams "Visual Studio 16 2019" "Win32"
popd
GOTO:EOF

:build2019x64
mkdir build-win-vs2019-x64
pushd build-win-vs2019-x64
call :cmakeParams "Visual Studio 16 2019" "x64"
popd
GOTO:EOF


:buildMinGW
mkdir build-win-MinGW-x64
pushd build-win-MinGW-x64
call :cmakeParams "MinGW Makefiles" "x64"
popd
GOTO:EOF


:cmakeParams
cmake -G "%~1" -A "%~2" ^
  -DBUILD_DOCS=OFF ^
  -DBUILD_EXAMPLES=OFF ^
  -DBUILD_PERF_TESTS=OFF ^
  -DBUILD_PROTOBUF=OFF ^
  -DBUILD_SHARED_LIBS=%BUILD_SHARED% ^
  -DBUILD_TESTS=OFF ^
  -DBUILD_WITH_DEBUG_INFO=OFF ^
  -DBUILD_WITH_STATIC_CRT=OFF ^
  -DBUILD_IPP_IW=ON ^
  -DBUILD_ITT=ON ^
  -DBUILD_JASPER=ON ^
  -DBUILD_JPEG=ON ^
  -DBUILD_PNG=ON ^
  -DBUILD_TBB=ON ^
  -DBUILD_TIFF=ON ^
  -DBUILD_WEBP=ON ^
  -DBUILD_ZLIB=ON ^
  -DWITH_EIGEN=OFF ^
  -DWITH_FFMPEG=OFF ^
  -DBUILD_opencv_dnn=OFF ^
  -DBUILD_opencv_world=ON ^
  ..
GOTO:EOF
只是换了个编译器，但是出错了
1
请选择要生成的选项并回车: 0)ALL，1)VS2015-x86，2)VS2015-x64，3)VS2017-x86，4)VS2017-x64，5)VS2019-x86，6)VS2019-x64，7)MinGW:
Please Select VS Ver: 0)ALL，1)VS2015-x86，2)VS2015-x64，3)VS2017-x86，4)VS2017-x64，5)VS2019-x86，6)VS2019-x64，7)MinGW:
7
A subdirectory or file build-win-MinGW-x64 already exists.
CMake Error at CMakeLists.txt:113 (enable_language):
  Generator        

    MinGW Makefiles

  does not support platform specification, but platform

    x64

  was specified.


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

**Comment by benjaminwan** [comment]
必须用 vs编译，mingw不支持
