### ISSUE TITLE
windows下用anaconda配置好环境，但是不知道怎么运行，怎么编译psenet呢

### ISSUE THREAD

**Issue by kyleceeport** [ouyanghuiyu/chineseocr_lite#40]
![image](https://user-images.githubusercontent.com/56183077/76676058-c20bbd00-65fa-11ea-8f29-3d98fe1a6c8d.png)
这段代码在这种情况下怎么运行，还是这个工程只能云linux来实现？

**Comment by michaelhadoop** [comment]
python3.6 非python3.6环境需要重新执行

**Comment by kyleceeport** [comment]
我装的是py36，也就是说在windows下，只要用anaconda配置好需要的环境，直接运行ａpp.py,然后调试就可以了是吧

**Comment by WestbrookZero** [comment]
> python3.6 非python3.6环境需要执行这条命令
请问是哪条命令？

**Comment by DarrenLee618** [comment]
我是用vs编译在windows下跑通的

**Comment by WestbrookZero** [comment]
> 我是用vs编译在windows下跑通的

请问一下，你具体是用vs编译在windows下怎么跑通的？

**Comment by DarrenLee618** [comment]
> 请问一下，你具体是用vs编译在windows下怎么跑通的？

vs编译生成pyd文件，python可以直接调用pyd文件
