### ISSUE TITLE
关于Android Studio编译cannot use 'throw' with exceptions disabled错误的问题

### ISSUE THREAD

**Issue by kongzue** [ouyanghuiyu/chineseocr_lite#409]
冒昧的问一下`error: cannot use 'throw' with exceptions disabled`改如何解决呢？
![image](https://user-images.githubusercontent.com/10115359/163022828-e772889f-5cd7-4f91-894a-42128b5f3c5b.png)

**Comment by sa1225** [comment]
> 冒昧的问一下`error: cannot use 'throw' with exceptions disabled`改如何解决呢？ ![image](https://user-images.githubusercontent.com/10115359/163022828-e772889f-5cd7-4f91-894a-42128b5f3c5b.png)

请问您怎么解决的，我也遇到这个问题了orz

**Comment by benjaminwan** [comment]
ncnn cmake注释掉一行

**Comment by sa1225** [comment]
已解决，谢谢！
