### ISSUE TITLE
可以去除返回的框结果Bitmap么？

### ISSUE THREAD

**Issue by mz5210** [ouyanghuiyu/chineseocr_lite#428]
如果需要的话，需要怎么修改？

**Comment by benjaminwan** [comment]
是指Android版吗？意思是完全不使用bitmap，把bitmap相关的代码移除吗？可以做到的

**Comment by mz5210** [comment]
> 

感谢回复！是的，指的安卓版本。请问如果要修改的话是需要自己去改C的代码么?还是已经有封装好的api在Java层调用呢？

**Comment by benjaminwan** [comment]
需要改C代码OcrResultUtils.cpp，把boxImg相关的删除，以及返回的数据类OcrResult.kt，把var boxImg: Bitmap删除；
然后把main.cpp里detect方法最后一行返回数据的参数去除boxImg

**Comment by mz5210** [comment]
> 需要改C代码OcrResultUtils.cpp，把boxImg相关的删除，以及返回的数据类OcrResult.kt，把var boxImg: Bitmap删除； 然后把main.cpp里detect方法最后一行返回数据的参数去除boxImg

感谢回复！明白了。
