### ISSUE TITLE
调整utils里的宽高扩增后，识别效果不好

### ISSUE THREAD

**Issue by ht-dep** [ouyanghuiyu/chineseocr_lite#43]
` size  = ( int(size[0] + min_size*alph ) , int(size[1]  +  min_size*alph) )`

**Comment by ouyanghuiyu** [comment]
> ` size = ( int(size[0] + min_size*alph ) , int(size[1] + min_size*alph) )`
可以尝试将alph值改小点，0.25 -> 0.15

**Comment by ht-dep** [comment]
3Q，666
