### ISSUE TITLE
运行app.py后文件缺失，网上找了许多方法无法解决，求助

### ISSUE THREAD

**Issue by kyleceeport** [ouyanghuiyu/chineseocr_lite#45]
![图片](https://user-images.githubusercontent.com/56183077/76696118-d4e9c480-66c2-11ea-8a3c-2659a44861b6.png)

![图片](https://user-images.githubusercontent.com/56183077/76696385-d072db00-66c5-11ea-961f-f385d9a74e31.png)
![图片](https://user-images.githubusercontent.com/56183077/76699101-f3f94e00-66e4-11ea-83ab-432a1e11be03.png)

这是在用anaconda配置好环境后，在IDEA和cmd中出错都是这个， 找不到对应的包或者模块导入，在网上找了许多方法无法解决，本人是在Windows下搭建运行，不能像Ubuntu那样下载运行.so文件，也不能使用make，求助这里面的模块属于python的哪些包

**Comment by ouyanghuiyu** [comment]
> ![图片](https://user-images.githubusercontent.com/56183077/76696118-d4e9c480-66c2-11ea-8a3c-2659a44861b6.png)
> 
> ![图片](https://user-images.githubusercontent.com/56183077/76696385-d072db00-66c5-11ea-961f-f385d9a74e31.png)
> ![图片](https://user-images.githubusercontent.com/56183077/76699101-f3f94e00-66e4-11ea-83ab-432a1e11be03.png)
> 
> 这是在用anaconda配置好环境后，在IDEA和cmd中出错都是这个， 找不到对应的包或者模块导入，在网上找了许多方法无法解决，本人是在Windows下搭建运行，不能像Ubuntu那样下载运行.so文件，也不能使用make，求助这里面的模块属于python的哪些包

我的.so文件是linux下的，你可以尝试在windows下使用docker

**Comment by vba34520** [comment]
欢迎查阅[Python构建快速高效的中文文字识别OCR](https://blog.csdn.net/lly1122334/article/details/104752851)，感谢#50 DarrenLee618大佬

**Comment by ouyanghuiyu** [comment]
> 欢迎查阅[Python构建快速高效的中文文字识别OCR](https://blog.csdn.net/lly1122334/article/details/104752851)，感谢#50 DarrenLee618大佬

66666 我在readme 更新下，放上你的链接
