### ISSUE TITLE
cpp demo OcrLiteOnnx VS2019编译错误

### ISSUE THREAD

**Issue by zhaokaixs** [ouyanghuiyu/chineseocr_lite#450]
![image](https://github.com/DayBreak-u/chineseocr_lite/assets/7833585/61c43f67-1c63-416b-812b-2534868203e8)

**Comment by benjaminwan** [comment]
如果自己整合依赖库，需要注意库的版本。

**Comment by zhaokaixs** [comment]
> 如果自己整合依赖库，需要注意库的版本。

谢谢  看错版本了
