### ISSUE TITLE
VS编译DLL动态库想做纯静态连接的DLL

### ISSUE THREAD

**Issue by zhaokaixs** [ouyanghuiyu/chineseocr_lite#451]
目前的DLL依赖
![image](https://github.com/DayBreak-u/chineseocr_lite/assets/7833585/99c41272-1050-4c6a-95aa-1e4f6accb591)
如果我想用/MT 编译这个DLL， 应该是把opencv和onnx的库 自己编译成/mt的吧？

**Comment by benjaminwan** [comment]
对

**Comment by zhaokaixs** [comment]
已成功 感谢
