### ISSUE TITLE
不需要竖着的文本检测

### ISSUE THREAD

**Issue by sunjunlishi** [ouyanghuiyu/chineseocr_lite#46]
作者你好，我调试你的ncnn代码，效果非常不错，特别是检测。
我正在往项目上用，你确实给很多的我这类的人，提供了生存之道。

我实际应用不需要竖着的文字检测，有办法解决，或者你之前有这类模型（不用检测竖着的问题）
![1](https://user-images.githubusercontent.com/11845664/76716128-171a1100-676a-11ea-8719-3e4fa3fa28ec.png)
![2](https://user-images.githubusercontent.com/11845664/76716135-1da88880-676a-11ea-8d04-1b1a9ee0a3fc.png)

**Comment by sunjunlishi** [comment]
1一个竖着的问题，一个 粘连，本质就是竖着的权重多了。
能联系你吗，可以奉上酬劳。

**Comment by ouyanghuiyu** [comment]
> 1一个竖着的问题，一个 粘连，本质就是竖着的权重多了。
> 能联系你吗，可以奉上酬劳。

你对延迟要求高吗，不高的话可以把long_size 调高点再试试看

**Comment by sunjunlishi** [comment]
对延时有要求。调大貌似没有太大影响。我看看你的算法吧。谢谢了。

**Comment by ouyanghuiyu** [comment]
> 对延时有要求。调大貌似没有太大影响。我看看你的算法吧。谢谢了。

你qq多少，把示例给我试试看

**Comment by ouyanghuiyu** [comment]
> 对延时有要求。调大貌似没有太大影响。我看看你的算法吧。谢谢了。

ncnn的psenet没实现核扩展，后期我看能不能实现一下，会对粘连文本有很大的改善

**Comment by sunjunlishi** [comment]
343449684 海豚，谢谢了

**Comment by ouyanghuiyu** [comment]
> 343449684 海豚，谢谢了

我psenet加了核扩展后的结果，效果会好一些，晚上我更新一下代码
![image](https://user-images.githubusercontent.com/42023607/76732156-f7024600-6799-11ea-893c-b2565fbcc806.png)

**Comment by sunjunlishi** [comment]
![2](https://user-images.githubusercontent.com/11845664/76767906-41ed7f00-67d5-11ea-84f1-c35ac55f9adb.png)
几乎完美解决了。
![1](https://user-images.githubusercontent.com/11845664/76767679-f2a74e80-67d4-11ea-9c11-49adeda6256d.png)
对了解决 “一”位置问题会不会影响类似右边问题。还有上下少点像素

**Comment by sunjunlishi** [comment]
![2](https://user-images.githubusercontent.com/11845664/76767906-41ed7f00-67d5-11ea-84f1-c35ac55f9adb.png)
几乎完美解决了。
![1](https://user-images.githubusercontent.com/11845664/76767679-f2a74e80-67d4-11ea-9c11-49adeda6256d.png)
对了解决 “一”位置问题会不会影响类似右边问题。还有上下少点像素

**Comment by sunjunlishi** [comment]
![3](https://user-images.githubusercontent.com/11845664/76774445-e58f5d00-67de-11ea-93b9-d060730a212a.png)

**Comment by ouyanghuiyu** [comment]
PseAdaptor(preds, contoursMap, 0.7311, 10, 1);
可以尝试调一下这个阈值0.7311 适用你的场景

**Comment by sunjunlishi** [comment]
我更改了，控制二值化的；实际自己也可以 写点分割方法，你的原理思路是什么我还没看明白，关于扩展核。

**Comment by sunjunlishi** [comment]
扩展核写的不错
	cv::connectedComponents(kernels[features.c - 1], label, 4);（选择第一个核，因为 当时 pushback，最后一个就是第一个）

	for (int idx = features.c - 2; idx >= 0; --idx) 前面的所有，对第一个进行合并。


对了能要下你联系方式 邮箱 ？

**Comment by ouyanghuiyu** [comment]
> 扩展核写的不错
> cv::connectedComponents(kernels[features.c - 1], label, 4);（选择第一个核，因为 当时 pushback，最后一个就是第一个）
> 
> ```
> for (int idx = features.c - 2; idx >= 0; --idx) 前面的所有，对第一个进行合并。
> ```
> 
> 对了能要下你联系方式 邮箱 ？

760997646@qq.com
