### ISSUE TITLE
识别模型怎么训练

### ISSUE THREAD

**Issue by Tony1236** [ouyanghuiyu/chineseocr_lite#47]
你好，识别模型是怎么训练的，会开源代码吗

**Comment by ouyanghuiyu** [comment]
是使用chineseocr中的训练方案

**Comment by Tony1236** [comment]
好的，谢谢，YCG09/chinese_ocr中使用是的中文合成数据集有360w张图片，而作者生成的数据集大概有多少啊

**Comment by ouyanghuiyu** [comment]
> 好的，谢谢，YCG09/chinese_ocr中使用是的中文合成数据集有360w张图片，而作者生成的数据集大概有多少啊

差不多 也是这是数量

**Comment by Tony1236** [comment]
非常感谢

**Comment by Tony1236** [comment]
作者，你好，crnn模型你是不定长训练的吗
