### ISSUE TITLE
vertical text traning

### ISSUE THREAD

**Issue by yangsuhui** [ouyanghuiyu/chineseocr_lite#5]
hi, I looked your crnn_lite.py and crnn_full.py ，according to your readme ,crnn_lite.py is the network trained for vertical text recognition, but the difference between orign and vertical text recognition network is what?
I saw the crnn_lite is also like crnn_full ,So could you tell me the difference between the orign and vertical text recognition networks?
Thank you very much!

**Comment by ouyanghuiyu** [comment]
crnn_lite is same as crnn_full,It's just the model size。vertical text traning is same as normal text，Just the data set is made differently。vertical text is like this
![171583317050_ pic_hd](https://user-images.githubusercontent.com/42023607/75869381-72800100-5e44-11ea-803a-81627b3b82fa.jpg)

**Comment by yangsuhui** [comment]
oh,ok.
one more question, the lable_map_dict  =  { 0 : "hengdao",  1:"hengzhen",  2:"shudao",  3:"shuzhen"} in the config.py is what?
could you give me some examples of jpgs like  "hengdao", "hengzhen",  "shudao",  "shuzhen" in the config.py ? thank you

**Comment by ouyanghuiyu** [comment]
hendao: like
![image](https://user-images.githubusercontent.com/42023607/75872292-d99fb480-5e48-11ea-9b9f-77643993994a.png)
hengzheng：like 
![image](https://user-images.githubusercontent.com/42023607/75872231-c260c700-5e48-11ea-8664-044c38305f33.png)
shudao: like 
![image](https://user-images.githubusercontent.com/42023607/75872327-e8866700-5e48-11ea-9a10-0b16183ff4c4.png)
shuzhen: like 
![image](https://user-images.githubusercontent.com/42023607/75872358-f4722900-5e48-11ea-8e57-df3d01ca93eb.png)
Used to determine the direction of a text line
