### ISSUE TITLE
Windows直接执行Make命令报错，求大佬写个CMakeLists

### ISSUE THREAD

**Issue by vba34520** [ouyanghuiyu/chineseocr_lite#50]
Windows直接执行Make命令报错，求大佬写个CMakeLists

![image](https://user-images.githubusercontent.com/40198281/76735014-0cc63a00-679f-11ea-9458-20f497fe34cd.png)

#48 大佬表示根据Makefile写个CMakeLists.txt，利用cmake生成sln文件，用Visual Studio编译成Windows平台DLL库，再给python调用

对于这方面实在是无从下手，求指教，跪谢~~~

**Comment by DarrenLee618** [comment]
windows上还是vs编译吧，我用的是vc2017, 生成pyd文件，python就可以直接调用了

**Comment by vba34520** [comment]
> windows上还是vs编译吧，我用的是vc2017, 生成pyd文件，python就可以直接调用了

前辈您好，我尝试用CMake去进行编译产生.sln，但是没有任何东西产生报错`Error in configuration process, project files may be invalid`

晚辈对编译方面经验浅薄，能否打扰前辈时间指导一下？
万分感谢，祝生活愉快！

**Comment by DarrenLee618** [comment]
> windows上还是vs编译吧，我用的是vc2017, 生成pyd文件，python就可以直接调用了
> 
> 前辈您好，我尝试用CMake去进行编译产生.sln，但是没有任何东西产生报错Error in configuration process, project files may be invalid
> 晚辈对编译方面经验浅薄，能否打扰前辈时间指导一下？
> 万分感谢，祝生活愉快！

不敢当，我对这方面也不熟悉，琢磨了两天才在windows平台上跑通，要不你留个联系方式，我加你

**Comment by vba34520** [comment]
> > windows上还是vs编译吧，我用的是vc2017, 生成pyd文件，python就可以直接调用了
> > 前辈您好，我尝试用CMake去进行编译产生.sln，但是没有任何东西产生报错Error in configuration process, project files may be invalid
> > 晚辈对编译方面经验浅薄，能否打扰前辈时间指导一下？
> > 万分感谢，祝生活愉快！
> 
> 不敢当，我对这方面也不熟悉，琢磨了两天才在windows平台上跑通，要不你留个联系方式，我加你

QQ：565681499
谢谢！

**Comment by vba34520** [comment]
欢迎查阅[Python构建快速高效的中文文字识别OCR](https://blog.csdn.net/lly1122334/article/details/104752851)，感谢DarrenLee618大佬
