### ISSUE TITLE
在Windows10的DockerDesktop上运行不起来，报psenet无法编译的错误

### ISSUE THREAD

**Issue by jidechao** [ouyanghuiyu/chineseocr_lite#53]
![错误](https://user-images.githubusercontent.com/62241490/76747212-c3ccb080-67b3-11ea-9fc0-22f4953c70e6.png)

**Comment by kyleceeport** [comment]
应该是跟我一样，因为Ｗｉｎｄｏｗｓ下不能执行ｍａｋｅ指令，也不能执行运行ｍａｋｅｆｉｌｅ,我也遇到一样的问题，现在也没有解决

**Comment by jidechao** [comment]
> 应该是跟我一样，因为Ｗｉｎｄｏｗｓ下不能执行ｍａｋｅ指令，也不能执行运行ｍａｋｅｆｉｌｅ,我也遇到一样的问题，现在也没有解决

可是我实在docker中执行的make命令，用的时ubutu18.04的镜像啊

**Comment by jidechao** [comment]
> 应该是跟我一样，因为Ｗｉｎｄｏｗｓ下不能执行ｍａｋｅ指令，也不能执行运行ｍａｋｅｆｉｌｅ,我也遇到一样的问题，现在也没有解决

查到原因了：需要单独安装python3-dev，即： apt-get update,apt-get install python3-dev

**Comment by vba34520** [comment]
欢迎查阅[Python构建快速高效的中文文字识别OCR](https://blog.csdn.net/lly1122334/article/details/104752851)，感谢#50 DarrenLee618大佬
