### ISSUE TITLE
relationship between ocr recognition and text orientation prediction

### ISSUE THREAD

**Issue by cvchongci** [ouyanghuiyu/chineseocr_lite#56]
hi, what is the relationship between ocr recognition and text orientation prediction?
before performing ocr recognition we should firstly predict the text orientation?
for text with different orientations, are different models used for ocr recognition? 

Thank you so much.

**Comment by daxingxingya** [comment]
<img width="777" alt="Screen Shot 2020-03-16 at 5 53 54 PM" src="https://user-images.githubusercontent.com/62248916/76764989-2a9b9b00-67af-11ea-93bd-950cb9c79ca7.png">

based on the above code, it seems that different models are used. is it right?
Thanks.

**Comment by ouyanghuiyu** [comment]
right

**Comment by cvchongci** [comment]
Thanks you very much.
