### ISSUE TITLE
ncnn project中文识别准确率低

### ISSUE THREAD

**Issue by zhengqicl** [ouyanghuiyu/chineseocr_lite#57]
你好，这边在windows环境下编译ncnn project，但是识别率好像有点低，不知道哪里有问题或者怎么调整？比如周杰伦那一张图片，下面是运行结果：
    C:\src\vc\NCNNOCRTest\x64\Release>NCNNOCRTest.exe 2.jpg 400
    缩放尺寸 (416, 384)
    psenet前向时间:1.55794s
    psenet decode 时间:0.0101029s
    boxzie2
    预测结果:
    最美的不是下雨天
    预测结果:
    是壁与座阀过雨的屋格
    角度检测和文字识别总时?0.578111s

**Comment by ouyanghuiyu** [comment]
是最新的代码吗，我看应该是中文索引的问题，因为找了错误和正确的字都只差一个索引
![image](https://user-images.githubusercontent.com/42023607/76818714-451e5480-6841-11ea-9ba5-129f13011719.png)

**Comment by zhengqicl** [comment]
是最新的代码，可能确实是索引的问题，因为vs中中文字符串变量太长无法编译，然后我用文本保存读取，谢谢啦

**Comment by ouyanghuiyu** [comment]
> 是最新的代码，可能确实是索引的问题，因为vs中中文字符串变量太长无法编译，然后我用文本保存读取，谢谢啦

读文件可能要把里面的转义字符“\” 去掉

**Comment by nihui** [comment]
我觉得，可以把这个字库，单独放在一个外部的txt里面加载，一行一个字 ...

**Comment by ouyanghuiyu** [comment]
> 我觉得，可以把这个字库，单独放在一个外部的txt里面加载，一行一个字 ...

收到！

**Comment by zhengqicl** [comment]
可以正常运行了，谢谢

**Comment by ouyanghuiyu** [comment]
已经改成从txt文件里读啦

**Comment by cqray1990** [comment]
@zhengqicl 
when  i run test my result is error codes，can  you help me thank you
psenet前向时间:1.13034s
psenet decode 时间:0.232561s
boxzie2
预测结果：
鏈€缇庣殑涓嶆槸涓嬮洦澶
鏄浘涓庝綘韬茶繃闆ㄧ殑灞嬫獝
角度检测和文字识别总时间:0.261597s

**Comment by littleSpongebob** [comment]
> ```
> 你好，这边在windows环境下编译ncnn project，但是识别率好像有点低，不知道哪里有问题或者怎么调整？比如周杰伦那一张图片，下面是运行结果：
> C:\src\vc\NCNNOCRTest\x64\Release>NCNNOCRTest.exe 2.jpg 400
> 缩放尺寸 (416, 384)
> psenet前向时间:1.55794s
> psenet decode 时间:0.0101029s
> boxzie2
> 预测结果:
> 最美的不是下雨天
> 预测结果:
> 是壁与座阀过雨的屋格
> 角度检测和文字识别总时?0.578111s
> ```



> ```
> 你好，这边在windows环境下编译ncnn project，但是识别率好像有点低，不知道哪里有问题或者怎么调整？比如周杰伦那一张图片，下面是运行结果：
> C:\src\vc\NCNNOCRTest\x64\Release>NCNNOCRTest.exe 2.jpg 400
> 缩放尺寸 (416, 384)
> psenet前向时间:1.55794s
> psenet decode 时间:0.0101029s
> boxzie2
> 预测结果:
> 最美的不是下雨天
> 预测结果:
> 是壁与座阀过雨的屋格
> 角度检测和文字识别总时?0.578111s
> ```

您好，因为在windows平台下编译ncnn_project有相关的教程么
