### ISSUE TITLE
模型问题

### ISSUE THREAD

**Issue by Tony1236** [ouyanghuiyu/chineseocr_lite#60]
大佬，我看你提供了很多训练好了的模型，crnn：lstm与dense哪个网络的效果好啊

**Comment by ouyanghuiyu** [comment]
lstm 效果较好，dense速度较快

**Comment by Tony1236** [comment]
恩恩，谢谢大佬，还有我对检测模型进行了测试，如下
![image](https://user-images.githubusercontent.com/53893913/76922127-d4436f00-690a-11ea-99d0-a38cd4156ecb.png)
发现一行文本被分割成多个检测框了，能不能一行文本就只检测成一个box啊

**Comment by ouyanghuiyu** [comment]
> 恩恩，谢谢大佬，还有我对检测模型进行了测试，如下
> ![image](https://user-images.githubusercontent.com/53893913/76922127-d4436f00-690a-11ea-99d0-a38cd4156ecb.png)
> 发现一行文本被分割成多个检测框了，能不能一行文本就只检测成一个box啊

这完全不影响呀，你可以做文本行连接

**Comment by Tony1236** [comment]
嗯嗯，还有就是身份证的检测会漏检啊
![image](https://user-images.githubusercontent.com/53893913/76923022-3ef5aa00-690d-11ea-8608-93659e62e0d8.png)

**Comment by ouyanghuiyu** [comment]
> 嗯嗯，还有就是身份证的检测会漏检啊
> ![image](https://user-images.githubusercontent.com/53893913/76923022-3ef5aa00-690d-11ea-8608-93659e62e0d8.png)

原图片发我下 ？

**Comment by Tony1236** [comment]
> > 嗯嗯，还有就是身份证的检测会漏检啊
> > ![image](https://user-images.githubusercontent.com/53893913/76923022-3ef5aa00-690d-11ea-8608-93659e62e0d8.png)
> 
> 原图片发我下 ？


检测模型对身份证和火车票的检测效果都不是很好，识别模型效果很好

**Comment by Tony1236** [comment]
![idcard-demo](https://user-images.githubusercontent.com/53893913/76929832-11fec280-6920-11ea-8c08-cfe9843d84ef.jpeg)

**Comment by ouyanghuiyu** [comment]
![image](https://user-images.githubusercontent.com/42023607/76932734-96ecda80-6926-11ea-95cb-f33fd759857f.png)

psenet 的pse.cpp 有点问题，修改了一下，你更新一下代码

**Comment by cvchongci** [comment]
厉害
