### ISSUE TITLE
请问这个是做什么的？if newH > 1.5* newW:

### ISSUE THREAD

**Issue by cvchongci** [ouyanghuiyu/chineseocr_lite#65]
我在读代码的时候看到model.py里面有句代码是：
if newH > 1.5* newW:
            partImg_array = np.rot90(partImg_array,1)

![image](https://user-images.githubusercontent.com/62248916/76934927-8d08ae80-6909-11ea-8cac-d3cd4e951143.png)

请问为什么要有这句操作？谢谢啦。

**Comment by ouyanghuiyu** [comment]
> 我在读代码的时候看到model.py里面有句代码是：
> if newH > 1.5* newW:
> partImg_array = np.rot90(partImg_array,1)
> 
> ![image](https://user-images.githubusercontent.com/62248916/76934927-8d08ae80-6909-11ea-8cac-d3cd4e951143.png)
> 
> 请问为什么要有这句操作？谢谢啦。

我把大概高大于宽的文本 旋转90度方便后面角度分类网络进行分类  https://github.com/ouyanghuiyu/chineseocr_lite/issues/5

**Comment by cvchongci** [comment]
谢谢，非常感谢。
