### ISSUE TITLE
请问ncnn的模型是定点模型还是浮点模型

### ISSUE THREAD

**Issue by 315654547** [ouyanghuiyu/chineseocr_lite#66]
请问ncnn的模型是定点模型还是浮点模型？

**Comment by ouyanghuiyu** [comment]
> 请问ncnn的模型是定点模型还是浮点模型？

float32 后期我试一下int8量化

**Comment by zqnnn** [comment]
> > 请问ncnn的模型是定点模型还是浮点模型？
> 
> float32 后期我试一下int8量化
请问您有尝试int8量化吗，应该怎么做啊？我直接用ncnn的Quantization Tools使用会报错
