### ISSUE TITLE
ncnn bulid failed

### ISSUE THREAD

**Issue by DavidLeeDVD** [ouyanghuiyu/chineseocr_lite#67]
在最后一步make时发生错误
CMakeFiles/Text_recognition.dir/build.make:86: recipe for target 'CMakeFiles/Text_recognition.dir/src/ocr.cpp.o' failed
make[2]: *** [CMakeFiles/Text_recognition.dir/src/ocr.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Text_recognition.dir/all' failed
make[1]: *** [CMakeFiles/Text_recognition.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Teragump** [comment]
建议贴上完整的编译打印信息

**Comment by DavidLeeDVD** [comment]
[ 25%] Building CXX object CMakeFiles/Text_recognition.dir/src/ocr.cpp.o
/media/ljj/新加卷/pycharmProjects/chineseocr_lite/ncnn_project/ocr/src/ocr.cpp: In function ‘std::vector<std::vector<cv::Point_<int> > > pse_deocde(const cv::Mat&, const cv::Mat&, std::vector<cv::RotatedRect>&, int, float, float)’:
/media/ljj/新加卷/pycharmProjects/chineseocr_lite/ncnn_project/ocr/src/ocr.cpp:204:27: error: ‘accumulate’ is not a member of ‘std’
         double sum = std::accumulate(std::begin(scores), std::end(scores), 0.0);
                           ^~~~~~~~~~
/media/ljj/新加卷/pycharmProjects/chineseocr_lite/ncnn_project/ocr/src/ocr.cpp:204:27: note: suggested alternative:
In file included from /usr/local/include/opencv2/opencv.hpp:74:0,
                 from /media/ljj/新加卷/pycharmProjects/chineseocr_lite/ncnn_project/ocr/include/ocr.h:10,
                 from /media/ljj/新加卷/pycharmProjects/chineseocr_lite/ncnn_project/ocr/src/ocr.cpp:1:
/usr/local/include/opencv2/imgproc.hpp:2712:19: note:   ‘cv::accumulate’
 CV_EXPORTS_W void accumulate( InputArray src, InputOutputArray dst,
                   ^~~~~~~~~~
/media/ljj/新加卷/pycharmProjects/chineseocr_lite/ncnn_project/ocr/src/ocr.cpp:217:15: warning: unused variable ‘w’ [-Wunused-variable]
         float w = rect.size.width;
               ^
/media/ljj/新加卷/pycharmProjects/chineseocr_lite/ncnn_project/ocr/src/ocr.cpp:218:15: warning: unused variable ‘h’ [-Wunused-variable]
         float h = rect.size.height;
               ^
/media/ljj/新加卷/pycharmProjects/chineseocr_lite/ncnn_project/ocr/src/ocr.cpp: In member function ‘void OCR::detect(cv::Mat, int)’:
/media/ljj/新加卷/pycharmProjects/chineseocr_lite/ncnn_project/ocr/src/ocr.cpp:312:23: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for (int i = 0; i < rects.size() ; i++ ){
                     ~~^~~~~~~~~~~~~~
/media/ljj/新加卷/pycharmProjects/chineseocr_lite/ncnn_project/ocr/src/ocr.cpp:504:24: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (int i=0; i<res_pre.size();i++){
                       ~^~~~~~~~~~~~~~~
/media/ljj/新加卷/pycharmProjects/chineseocr_lite/ncnn_project/ocr/src/ocr.cpp:345:16: warning: unused variable ‘time2’ [-Wunused-variable]
         double time2 = static_cast<double>( cv::getTickCount());
                ^~~~~
CMakeFiles/Text_recognition.dir/build.make:86: recipe for target 'CMakeFiles/Text_recognition.dir/src/ocr.cpp.o' failed
make[2]: *** [CMakeFiles/Text_recognition.dir/src/ocr.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/Text_recognition.dir/all' failed
make[1]: *** [CMakeFiles/Text_recognition.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Teragump** [comment]
> /media/ljj/新加卷/pycharmProjects/chineseocr_lite/ncnn_project/ocr/src/ocr.cpp:204:27: error: ‘accumulate’ is not a member of ‘std’
double sum = std::accumulate(std::begin(scores), std::end(scores), 

当前最新的代码里面已经没有使用这个借口了，你应该用的是34929e88c51b098f7c81fc00fdda1467b069c6a7版本，建议更新一下试试；
另外这个报错跟编译环境有关，谷歌一下有很多链接可以参考：）
