### ISSUE TITLE
ncnn ocr build failed

### ISSUE THREAD

**Issue by light1003** [ouyanghuiyu/chineseocr_lite#68]
make时发生链接lib库错误关于libncnn.a，求帮助
[100%] Building CXX object CMakeFiles/Text_recognition.dir/src/RRLib.cpp.o
./test0318/ncnn_project/ocr/src/RRLib.cpp: In function 'void RRLib::copyToRotRectImg(cv::RotatedRect, cv::Mat&, cv::Mat&, cv::Mat&)':
./test0318/ncnn_project/ocr/src/RRLib.cpp:218:18: warning: variable 'src_roi' set but not used [-Wunused-but-set-variable]
         cv::Rect src_roi = Rect(0, 0, src.cols, src.rows);
                  ^
Linking CXX executable Text_recognition
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(net.cpp.o): In function `ncnn::Net::find_blob_index_by_name(char const*) const':
net.cpp:(.text+0x630): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(net.cpp.o): In function `ncnn::Net::find_layer_index_by_name(char const*) const':
net.cpp:(.text+0x6be): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(net.cpp.o): In function `ncnn::Extractor::input(char const*, ncnn::Mat const&)':
net.cpp:(.text+0x8e2): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(net.cpp.o): In function `ncnn::Extractor::extract(char const*, ncnn::Mat&)':
net.cpp:(.text+0x3d36): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(net.cpp.o): In function `ncnn::Net::load_param(ncnn::DataReader const&)':
net.cpp:(.text+0x5f49): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
net.cpp:(.text+0x5fee): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
net.cpp:(.text+0x60fa): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::compare(char const*) const'
net.cpp:(.text+0x6226): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
net.cpp:(.text+0x6420): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
net.cpp:(.text+0x647b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
net.cpp:(.text+0x64c7): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
net.cpp:(.text+0x6600): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
net.cpp:(.text+0x664f): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(net.cpp.o): In function `std::vector<ncnn::Blob, std::allocator<ncnn::Blob> >::_M_fill_insert(__gnu_cxx::__normal_iterator<ncnn::Blob*, std::vector<ncnn::Blob, std::allocator<ncnn::Blob> > >, unsigned long, ncnn::Blob const&)':
net.cpp:(.text._ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0x6bb): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(net.cpp.o):net.cpp:(.text._ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0x6fa): more undefined references to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)' follow
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(net.cpp.o): In function `std::vector<ncnn::Blob, std::allocator<ncnn::Blob> >::_M_fill_insert(__gnu_cxx::__normal_iterator<ncnn::Blob*, std::vector<ncnn::Blob, std::allocator<ncnn::Blob> > >, unsigned long, ncnn::Blob const&)':
net.cpp:(.text._ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0xc36): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
net.cpp:(.text._ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0xceb): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
net.cpp:(.text._ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0x123c): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
net.cpp:(.text._ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0x130b): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
net.cpp:(.text._ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0x13cb): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
net.cpp:(.text._ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0x1594): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_assign(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
net.cpp:(.text._ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_[_ZNSt6vectorIN4ncnn4BlobESaIS1_EE14_M_fill_insertEN9__gnu_cxx17__normal_iteratorIPS1_S3_EEmRKS1_]+0x175d): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::_M_create(unsigned long&, unsigned long)'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(bnll.cpp.o): In function `ncnn::BNLL::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]':
bnll.cpp:(.text+0x400): undefined reference to `_ZGVbN2v___exp_finite'
bnll.cpp:(.text+0x419): undefined reference to `_ZGVbN2v___exp_finite'
bnll.cpp:(.text+0x435): undefined reference to `_ZGVbN2v___log_finite'
bnll.cpp:(.text+0x451): undefined reference to `_ZGVbN2v___log_finite'
bnll.cpp:(.text+0x461): undefined reference to `_ZGVbN2v___exp_finite'
bnll.cpp:(.text+0x474): undefined reference to `_ZGVbN2v___exp_finite'
bnll.cpp:(.text+0x49a): undefined reference to `_ZGVbN2v___log_finite'
bnll.cpp:(.text+0x4c0): undefined reference to `_ZGVbN2v___log_finite'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(deconvolution.cpp.o): In function `ncnn::Deconvolution::forward(ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]':
deconvolution.cpp:(.text+0x545): undefined reference to `_ZGVbN2v___exp_finite'
deconvolution.cpp:(.text+0x563): undefined reference to `_ZGVbN2v___exp_finite'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(exp.cpp.o): In function `ncnn::Exp::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.1]':
exp.cpp:(.text+0x480): undefined reference to `_ZGVbN2vv___pow_finite'
exp.cpp:(.text+0x4ab): undefined reference to `_ZGVbN2vv___pow_finite'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(log.cpp.o): In function `ncnn::Log::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.1]':
log.cpp:(.text+0x511): undefined reference to `_ZGVbN2v___log_finite'
log.cpp:(.text+0x52d): undefined reference to `_ZGVbN2v___log_finite'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(lrn.cpp.o): In function `ncnn::LRN::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.1]':
lrn.cpp:(.text+0x7c9): undefined reference to `_ZGVbN2vv___pow_finite'
lrn.cpp:(.text+0x800): undefined reference to `_ZGVbN2vv___pow_finite'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(power.cpp.o): In function `ncnn::Power::forward_inplace(ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]':
power.cpp:(.text+0x380): undefined reference to `_ZGVbN2vv___pow_finite'
power.cpp:(.text+0x3ab): undefined reference to `_ZGVbN2vv___pow_finite'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(reduction.cpp.o): In function `int ncnn::reduction_op<ncnn::reduction_op_sumsexp<float>, std::plus<float> >(ncnn::Mat const&, ncnn::Mat&, float, bool, bool, bool, ncnn::Option const&) [clone ._omp_fn.123]':
reduction.cpp:(.text+0x8c10): undefined reference to `_ZGVbN2v___exp_finite'
reduction.cpp:(.text+0x8c29): undefined reference to `_ZGVbN2v___exp_finite'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(reduction.cpp.o): In function `int ncnn::reduction_op<ncnn::reduction_op_sumsexp<float>, std::plus<float> >(ncnn::Mat const&, ncnn::Mat&, float, bool, bool, bool, ncnn::Option const&) [clone ._omp_fn.122]':
reduction.cpp:(.text+0xf218): undefined reference to `_ZGVbN2v___exp_finite'
reduction.cpp:(.text+0xf234): undefined reference to `_ZGVbN2v___exp_finite'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(reduction.cpp.o): In function `int ncnn::reduction_op_keepdims<ncnn::reduction_op_sumsexp<float>, std::plus<float> >(ncnn::Mat const&, ncnn::Mat&, float, bool, bool, bool, ncnn::Option const&) [clone ._omp_fn.114]':
reduction.cpp:(.text+0xf6b8): undefined reference to `_ZGVbN2v___exp_finite'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(reduction.cpp.o):reduction.cpp:(.text+0xf6d4): more undefined references to `_ZGVbN2v___exp_finite' follow
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(binaryop.cpp.o): In function `int ncnn::binary_op<ncnn::binary_op_pow<float> >(ncnn::Mat const&, ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) [clone ._omp_fn.54]':
binaryop.cpp:(.text+0x36e6): undefined reference to `_ZGVbN2vv___pow_finite'
binaryop.cpp:(.text+0x370d): undefined reference to `_ZGVbN2vv___pow_finite'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(binaryop.cpp.o): In function `int ncnn::binary_op<ncnn::binary_op_pow<float> >(ncnn::Mat const&, ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) [clone ._omp_fn.56]':
binaryop.cpp:(.text+0x3a8c): undefined reference to `_ZGVbN2vv___pow_finite'
binaryop.cpp:(.text+0x3ab3): undefined reference to `_ZGVbN2vv___pow_finite'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(binaryop.cpp.o): In function `int ncnn::binary_op<ncnn::binary_op_pow<float> >(ncnn::Mat const&, ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) [clone ._omp_fn.60]':
binaryop.cpp:(.text+0x420b): undefined reference to `_ZGVbN2vv___pow_finite'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(binaryop.cpp.o):binaryop.cpp:(.text+0x4229): more undefined references to `_ZGVbN2vv___pow_finite' follow
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(deconvolutiondepthwise.cpp.o): In function `ncnn::DeconvolutionDepthWise::forward(ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.0]':
deconvolutiondepthwise.cpp:(.text+0x7e0): undefined reference to `_ZGVbN2v___exp_finite'
deconvolutiondepthwise.cpp:(.text+0x7f8): undefined reference to `_ZGVbN2v___exp_finite'
./test0318/ncnn_project/ocr/ncnn/lib/libncnn.a(deconvolutiondepthwise.cpp.o): In function `ncnn::DeconvolutionDepthWise::forward(ncnn::Mat const&, ncnn::Mat&, ncnn::Option const&) const [clone ._omp_fn.1]':
deconvolutiondepthwise.cpp:(.text+0xfd4): undefined reference to `_ZGVbN2v___exp_finite'
deconvolutiondepthwise.cpp:(.text+0xff2): undefined reference to `_ZGVbN2v___exp_finite'
collect2: error: ld returned 1 exit status
make[2]: *** [Text_recognition] Error 1
make[1]: *** [CMakeFiles/Text_recognition.dir/all] Error 2
make: *** [all] Error 2

**Comment by ouyanghuiyu** [comment]
你是在linux环境下吗， 最好是自己去ncnn拉下master代码，自己编译一下，生成.h和.a文件

**Comment by light1003** [comment]
> 你是在linux环境下吗， 最好是自己去ncnn拉下master代码，自己编译一下，生成.h和.a文件

非常感谢，已经解决
