### ISSUE TITLE
缺少包

### ISSUE THREAD

**Issue by Lie-huo** [ouyanghuiyu/chineseocr_lite#7]
ModuleNotFoundError: No module named 'torchvision.models.utils'，但是我已经安装了'torchvision

**Comment by ouyanghuiyu** [comment]
> torchvison==0.4.0

**Comment by Lie-huo** [comment]
> torchvison==0.4.0

我用的是windows系统，torchvison==0.2.2，好像是对应着linux系统的torchvison==0.4.2，还是报错，看来是两个系统的torchvison有些差别。

**Comment by ouyanghuiyu** [comment]
> > torchvison==0.4.0
> 
> 我用的是windows系统，torchvison==0.2.2，好像是对应着linux系统的torchvison==0.4.2，还是报错，看来是两个系统的torchvison有些差别。

可以注释掉这个导入包，把下面加载mbv2预训练模型也注释了，这是在训练中用的

**Comment by ahxxm** [comment]
`python app.py`需要以下依赖：

```
web.py
numpy
scipy
pillow
torch
torchvision
opencv-contrib-python
```

另外如果python版本不是3.6，还需要重新编一份pse.so :

```bash
# ImportError: Python version mismatch: module was compiled for Python 3.6, but the interpreter version is incompatible: 3.8.1 (default, Jan 22 2020, 06:38:00) 

cd psenet/pse
mv pse.so pse.so.3.6
make
```

**Comment by windly4548** [comment]
我的环境是ubuntu14，使用 ufoym/deepo镜像包，执行python3 app.py 8080后出现错误：
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    from model import  text_predict,crnn_handle
  File "/data/chineseocr_lite/model.py", line 1, in <module>
    from config import  *
  File "/data/chineseocr_lite/config.py", line 40, in <module>
    from crnn.keys import  alphabetChinese as alphabet
  File "/data/chineseocr_lite/crnn/__init__.py", line 3, in <module>
    from .CRNN import CRNNHandle
ModuleNotFoundError: No module named 'crnn.CRNN'

**Comment by ouyanghuiyu** [comment]
> 我的环境是ubuntu14，使用 ufoym/deepo镜像包，执行python3 app.py 8080后出现错误：
> Traceback (most recent call last):
> File "app.py", line 12, in
> from model import text_predict,crnn_handle
> File "/data/chineseocr_lite/model.py", line 1, in
> from config import *
> File "/data/chineseocr_lite/config.py", line 40, in
> from crnn.keys import alphabetChinese as alphabet
> File "/data/chineseocr_lite/crnn/**init**.py", line 3, in
> from .CRNN import CRNNHandle
> ModuleNotFoundError: No module named 'crnn.CRNN'

你好，我今天push的时候不小心吧crnn目录下的CRNN.py 删了，现在传了，你更新一下
