### ISSUE TITLE
提供caffe模型

### ISSUE THREAD

**Issue by sunjunlishi** [ouyanghuiyu/chineseocr_lite#71]
你好作者：你的提供ncnn模型很好，但是速度一般是1.1s左右；我有点得寸进尺，你能提供psnet文字检测的caffe模型吗。因为ncnn没加速，caffe是加速的，速度应该可以提高一倍多（cpu版本）

**Comment by ouyanghuiyu** [comment]
> 你好作者：你的提供ncnn模型很好，但是速度一般是1.1s左右；我有点得寸进尺，你能提供psnet文字检测的caffe模型吗。因为ncnn没加速，caffe是加速的，速度应该可以提高一倍多（cpu版本）

你可以尝试从torch转到caffe，或者转onnx用其他框架加速，还是你是要用在手机端？

**Comment by sunjunlishi** [comment]
手机端用ncnn就可以，手机端ncnn的 neon加速指令，做的非常好。ncnn就pc端的cpu没有用单指令多数据集指令加速。caffe可以用openblas或者eigen算法库，加速

**Comment by sunjunlishi** [comment]
还有我发现你的检测库处理 身份证非常Easy。实际可以用在车牌检测的细节定位上，进行纠正。提升车牌的识别效果。用处还是有的，甚至 用在 智能应用，辅助学生学习app识别应用上。

**Comment by ouyanghuiyu** [comment]
> 手机端用ncnn就可以，手机端ncnn的 neon加速指令，做的非常好。ncnn就pc端的cpu没有用单指令多数据集指令加速。caffe可以用openblas或者eigen算法库，加速

是不是可以尝试通过这个改一下？ https://github.com/longcw/pytorch2caffe

**Comment by sunjunlishi** [comment]
你是怎么转ncnn的，不会是 直接读取pth文件就可以直接转换，不用自己写代码。
我看pytorch转caffe的，貌似要知道每层参数，自己手动写转换脚本吧。

**Comment by ouyanghuiyu** [comment]
torch->onnx->ncnn  https://github.com/Tencent/ncnn

**Comment by ouyanghuiyu** [comment]
> 你是怎么转ncnn的，不会是 直接读取pth文件就可以直接转换，不用自己写代码。
> 我看pytorch转caffe的，貌似要知道每层参数，自己手动写转换脚本吧。

一般框架之间转换都要自己写脚本

**Comment by sunjunlishi** [comment]
对了仅仅那个我也转不了。我看你的网络不仅仅是 psenet 还是 + mobilev2;
模型小，效果好；
能提供onnx模型，其他人不知道可以转

**Comment by sunjunlishi** [comment]
你能提供caffe模型？你这3k星，一个人奉上10元，也都 30k了。

**Comment by sunjunlishi** [comment]
@ouyanghuiyu 方便联系你。公开联系麻烦的化，你可以联系我343449684 海豚。急迫，谢谢
