### ISSUE TITLE
AngleNet的训练问题

### ISSUE THREAD

**Issue by timbryant** [ouyanghuiyu/chineseocr_lite#73]
您好！
非常感谢您的工作成果，对您的工作非常有兴趣。在代码中有一个调用AngleNet网络模型的过程，关于网络训练方面有几个问题想问下您：
1、请问是如何训练该网络？是仅仅拿四种类别对应的图像训练一个分类网络吗？
2：训练的数据集是如何的？四个种类的图片大概有几张？
3：其他两个网络的训练都是按照ReadMe里面放的链接来训练的嘛？
期待您的回复，谢谢您！

**Comment by ouyanghuiyu** [comment]
1、对，就是训练分类网络
2、四类大概20w张吧（几张？你这问的！）
3、对，按readme的链接训练的

**Comment by timbryant** [comment]
不好意思，不好意思。表述有问题，不应该说几张的。请见谅

**Comment by ouyanghuiyu** [comment]
> 不好意思，不好意思。表述有问题，不应该说几张的。请见谅

没事没事 开个玩笑
