### ISSUE TITLE
在安卓端psenet模型加载失败，想请教一下这种情况如何debug？

### ISSUE THREAD

**Issue by Arctanxy** [ouyanghuiyu/chineseocr_lite#77]
psenet的load_param和load_model两个方法的返回值都是-1。
其他几个模型加载正常。
可能是什么原因呢？

**Comment by ouyanghuiyu** [comment]
你是用这个项目的代码吗

**Comment by Arctanxy** [comment]
> 你是用这个项目的代码吗

谢谢，是用的这个项目下的代码，问题已经解决了，是我在复制模型文件到sd卡的过程中出了问题。

**Comment by ouyanghuiyu** [comment]
> > 你是用这个项目的代码吗
> 
> 谢谢，是用的这个项目下的代码，问题已经解决了，是我在复制模型文件到sd卡的过程中出了问题。

欢迎贡献 安卓的demo
