### ISSUE TITLE
请问您是如何把模型做的这么小的？

### ISSUE THREAD

**Issue by JasonZhangS** [ouyanghuiyu/chineseocr_lite#79]
chineseocr_lite 的模型比chineseocr（https://github.com/chineseocr/chineseocr）小很多。请问您采取了哪些方法把模型做的这么小？

**Comment by ouyanghuiyu** [comment]
模型基本都改了，使用一些轻量的网络结构

**Comment by Whu-wxy** [comment]
@ouyanghuiyu 有没有做量化或者其他处理呢？psenet_lite_mbv2这个

**Comment by ouyanghuiyu** [comment]
@Whu-wxy 没有做的，你们可以自己做一下

**Comment by Whu-wxy** [comment]
@ouyanghuiyu 厉害了，我看这个模型检测效果好好呀，还是多语言的

**Comment by winnerselfHX** [comment]
@DayBreak-u  paddleocr的模型转化成onnx格式能直接使用吗？ 怎么才能使用或者是不能使用
