### ISSUE TITLE
Anglenet的输出是什么意思？

### ISSUE THREAD

**Issue by Kay-Tian** [ouyanghuiyu/chineseocr_lite#8]
想请教一下，anglenet的输出是什么意思？看ncnn_project里给的示例是判断文本行的正反，但是网络输出了四个分类结果，后面两个是什么意思？这部分是否有相关的参考文档？

**Comment by ouyanghuiyu** [comment]
参考https://github.com/ouyanghuiyu/chineseocr_lite/issues/5

**Comment by Kay-Tian** [comment]
谢谢
