### ISSUE TITLE
Centos7 python3.6.8 下只要浏览器上一上传图片（700x400.jpg 69kb）识别，程序就中断，没有相关详细的报错信息

### ISSUE THREAD

**Issue by lgs3137** [ouyanghuiyu/chineseocr_lite#88]
![image](https://user-images.githubusercontent.com/1278141/77378190-4820c400-6db0-11ea-8864-6cb3a8952832.png)

**Comment by yuzi1949** [comment]
你看下后台，有没有报错信息，是不是：段错误（吐核）。我也遇到了跟你这个一样的情况

**Comment by lgs3137** [comment]
Mar 24 10:28:11 hcj kernel: python3[25859]: segfault at 1 ip 00007f49706aa434 sp 00007f4a0dbf8e10 error 6 in pse.so[7f497069a000+17000]
我看了下kernel的日志是 pse.so 报错了，但正常重复编译n次了

**Comment by lgs3137** [comment]
我试试把gcc升级到4.9.4版本再重新编译pse.so看看

**Comment by lgs3137** [comment]
@yuzi1949 果然升级gcc 4.9.4版本后重新编译pse.so后正常了~
