### ISSUE TITLE
关于ncnn_project模型准确率的问题

### ISSUE THREAD

**Issue by Arctanxy** [ouyanghuiyu/chineseocr_lite#92]
我用了100多张发票对ncnn_project下的模型进行测试，发现能正确识别税号的样本只有20%左右（那个yolov3版的chineseocr大概能识别出75%左右的税号）。
我把图片单独拿出来看了下，检测和识别的效果都不太理想，这是模型压缩之后造成的精度损失吗？
有什么方法可以优化吗？

**Comment by ouyanghuiyu** [comment]
你的发票字体小吗 ，lingsize调大点看看？

**Comment by Arctanxy** [comment]
字比较小吧，longsize调到960之后能识别出30%，再大的话，速度就有点慢了。

**Comment by Arctanxy** [comment]
谢谢大佬，我在自己的发票数据集上微调了一下psenet，现在效果好了点。另外，想问下大佬你的crnn是在那个数据集上训练的呀？@ouyanghuiyu

**Comment by ouyanghuiyu** [comment]
> 谢谢大佬，我在自己的发票数据集上微调了一下psenet，现在效果好了点。另外，想问下大佬你的crnn是在那个数据集上训练的呀？@ouyanghuiyu

你可以根据你自己的场景生成大量数据集进行训练，效果肯定好很多

**Comment by Arctanxy** [comment]
好的，谢谢
